### ISSUE TITLE
Using CPU contexts even after compiling with GPU

### ISSUE THREAD

**Issue by ranjanan** [dmlc/MXNet.jl#101]
So, I've compiled MXNet with CUDA enabled. When I use gpu contexts, everything works.
Now, when I use CPU contexts again, like:

``` julia
model = mx.FeedForward(mlp, context=mx.cpu())
```

I get the following error:

```
julia: symbol lookup error: /home/ubuntu/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so: undefined symbol: cblas_sgemm64_
```

Does this mean that when I compile with CUDA enabled, I've lost the choice of using CPU contexts? (It would be useful to have both in a situation where you're comparing training speeds on CPU and GPU)

**Comment by pluskid** [comment]
No, according to the error message, it means the system cannot locate the BLAS library on your system. If you installed it to non-standard location, make sure to add it to `LD_LIBRARY_PATH`. The default building script tries to use the Julia's internal openBLAS for compilation, but maybe you are using a different one?

**Comment by mcreel** [comment]
I'm not sure that this is the case. On an Amazon EC2 instance, I can switch between cpu and gpu when using Mocha.jl, but not when using MXNet.jl.  When MXNET has been built with gpu support, I get the above error when attempting to use the cpu backend. When I rebuild MXNet without GPU support, it works using the cpu backend. All of this without making changes to LD_LIBRARY_PATH. Thus, it seems to me that when a gpu build is configures,  libmxnet.so is built without including the possibility of using the cpu backend.
