### ISSUE TITLE
MXNet crashes on matrix multiplication

### ISSUE THREAD

**Issue by gabgoh** [dmlc/MXNet.jl#104]
The following code causes MXNet to crash on my windows machine.

```
julia> x = mx.ones((100,2))
mx.NDArray(100,2)

julia> y = mx.ones((2,100))
mx.NDArray(2,100)

julia> mx.dot(x,y)
mx.NDArray(100,100)

Press Enter or Esc to close console...
```

it works fine on the GPU, and on my other mac machine. Any clue why?

**Comment by gabgoh** [comment]
This appears to be a problem with the mxnet library itself, not the julia wrapper. Sorry for posting it here.

**Comment by vchuravy** [comment]
X-Ref: https://github.com/dmlc/mxnet/issues/2565

**Comment by iblis17** [comment]
It works on current master, close it now?
