### ISSUE TITLE
Training a MLP for regression

### ISSUE THREAD

**Issue by diegoacuna** [dmlc/MXNet.jl#105]
Hi, I'm trying to train a MLP for regression but I can't get the network to actually "learn"  in the training procedure. This is my code:

```
using MXNet
using Distributions

srand(100)

generate_dataset(media, var, tam) = rand(MvNormal(media, var), tam)
#Synthetic Function that generates the labels
f1(x1, x2) = sin(x1).*sin(x2)./(x1.*x2)

#Parameter Definition for the dataset generation
mean=[0.0;0.0]
var=[1.0 0.0;0.0 1.0]
tam=5000

datasetinput = generate_dataset(mean, var, tam)
datasetoutput = f1(datasetinput[1,:], datasetinput[2,:])

trainprovider = mx.ArrayDataProvider(:data => datasetinput, :label => datasetoutput)

data = mx.Variable(:data)
label = mx.Variable(:label)

fc1  = mx.FullyConnected(data = data, name=:fc1, num_hidden=20)
act1 = mx.Activation(data = fc1, name=:relu1, act_type=:relu)
fc2  = mx.FullyConnected(data = act1, name=:fc2, num_hidden=1)
cost = mx.LinearRegressionOutput(data=fc2, label=label, name = :loss)

model = mx.FeedForward(cost, context=mx.cpu())

optimizer = mx.SGD(lr=0.1, momentum=0.9, weight_decay=0.00001)
mx.fit(model, optimizer, trainprovider, n_epoch = 100)
```
and the output is:

```
WARNING: module mx should explicitly import transpose from Base
INFO: Start training on [CPU0]
INFO: Initializing parameters...
INFO: Creating KVStore...
INFO: Start training...
INFO: == Epoch 001 ==========
INFO: ## Training summary
INFO:           accuracy = 0.0000
INFO:               time = 0.3318 seconds
INFO: == Epoch 002 ==========
INFO: ## Training summary
INFO:           accuracy = 0.0000
INFO:               time = 0.0019 seconds
...
...
...
INFO: == Epoch 098 ==========
INFO: ## Training summary
INFO:           accuracy = 0.0000
INFO:               time = 0.0021 seconds
INFO: == Epoch 099 ==========
INFO: ## Training summary
INFO:           accuracy = 0.0000
INFO:               time = 0.0043 seconds
INFO: == Epoch 100 ==========
INFO: ## Training summary
INFO:           accuracy = 0.0000
INFO:               time = 0.0068 seconds
```

There is something wrong with the definition of my network? 

Thanks in advance.

**Comment by pluskid** [comment]
The default metric (accuracy) is not suitable for regression. You will probably need to use [MSE](https://github.com/dmlc/MXNet.jl/blob/master/src/metric.jl#L119) as the metric when calling `fit`.

**Comment by mcreel** [comment]
I believe that the above example works for regression if you change the last line to read
mx.fit(model, optimizer, eval_metric=mx.MSE(), trainprovider, n_epoch = 100)

I'm getting sensible output, with improvement during training, but I'm just getting started with MXNet.jl

**Comment by vchuravy** [comment]
@mcreel That is correct, the important distinction is that the `eval_metric` is not actually used for training, but only as output for the user.

**Comment by mcreel** [comment]
Thanks! I suggest putting the example code in the closed issue in a visible
place, as a quick example of a net used for regression, rather than
classification. As a new user, I found it helpful, for the way it provides
data to the net. With the code in a closed issue, few people with the same
doubts will find it.

<http://www.uab.cat/>

Michael Creel
*UAB, BGSE, MOVE*
Director, Dept. d'Economia I d'Història Econòmica


T +34 93 581 1696
web page <http://pareto.uab.es/mcreel>

**Comment by vchuravy** [comment]
That sounds like a good idea,would you mind opening up a PR?

**Comment by mcreel** [comment]
Sure, I'll do that.

<http://www.uab.cat/>

Michael Creel
*UAB, BGSE, MOVE*
Director, Dept. d'Economia I d'Història Econòmica


T +34 93 581 1696
web page <http://pareto.uab.es/mcreel>

**Comment by diegoacuna** [comment]
thanks all for your valuable comments, my example code is now working with your suggestions.

**Comment by mcreel** [comment]
Hi Diego,
Do you mind if I make a pull request using your code as an example? Or you
could make the request yourself if you prefer.
Michael

**Comment by diegoacuna** [comment]
Don't worry if you have the time you can make the PR, let me know!

**Comment by mcreel** [comment]
Hi Diego, I made a PR, with a version that adds a few comments. Thanks!

<http://www.uab.cat/>

Michael Creel
*UAB, BGSE, MOVE*
Director, Dept. d'Economia I d'Història Econòmica


T +34 93 581 1696
web page <http://pareto.uab.es/mcreel>
