### ISSUE TITLE
Unable to find function MXSymbolListAttr in library

### ISSUE THREAD

**Issue by kleinash** [dmlc/MXNet.jl#110]
Hi I am getting an error when running `mx.fit(model, optimizer, train_provider, n_epoch=20, eval_data=eval_provider)`

ERROR: LoadError: ccall: could not find function MXSymbolListAttr in library .julia/v0.4/MXNet/deps/usr/lib/libmxnet.so

I am on Ubuntu 14.04; Julia v0.4; Cuda 7.5

**Comment by vchuravy** [comment]
When did you last update MXNet the library?

**Comment by kleinash** [comment]
I update julia all the time - and yesterday when I got this error I tried to update the mxnet library, but it too is upset:

$ make -j$(nproc)

gets me this error:
collect2: error: ld returned 1 exit status
make: *** [bin/im2rec] Error 1

**Comment by kleinash** [comment]
I partitioned my drive, installed Ubuntu 16.04, Julia, MXNet.jl and everything works as expected perfectly. I installed the mxnet dependencies listed in the install instructions and there was no need to install mxnet separately and export its home directory. 

I will close this and go on to install cuda at a later stage on this partition.
