### ISSUE TITLE
Docs missing for Windows installation

### ISSUE THREAD

**Issue by niczky12** [dmlc/MXNet.jl#111]
I've been trying to install MXNet on windows, but get the following error after running `Pkg.add("MXNet")` and/or `Pkg.build("MXNet")`:

    INFO: Building MXNet
    INFO: Please follow the libmxnet documentation on how to build manually
    INFO: or to install pre-build packages:
    INFO: http://mxnet.readthedocs.org/en/latest/build.html#building-on-windows
    ================================[ ERROR: MXNet ]================================
    
    LoadError: Automatic building libxmnet on Windows is currently not supported yet.
    while loading C:\Users\bence.komarniczky\.julia\v0.4\MXNet\deps\build.jl, in expression starting on     line 20

    ================================================================================

    ================================[ BUILD ERRORS ]================================

    WARNING: MXNet had build errors.
    
     - packages with build errors remain installed in C:\Users\bence.komarniczky\.julia\v0.4
     - build the package(s) and all dependencies with `Pkg.build("MXNet")`
     - build a single package by running its `deps/build.jl` script

    ================================================================================`

I tried searching the docs and the issues, but the link is broken:
http://mxnet.readthedocs.org/en/latest/build.html#building-on-windows

Anyone managed to get MXNet working on Windows?

**Comment by pluskid** [comment]
Thanks for reporting this. The URL has been updated. The correct URL should be http://mxnet.readthedocs.io/en/latest/how_to/build.html#building-on-windows

**Comment by niczky12** [comment]
Thanks @pluskid ! This is very helpful.
