### ISSUE TITLE
3D convolution and deconvolution ?

### ISSUE THREAD

**Issue by jingpengwu** [dmlc/MXNet.jl#114]
All the documentation shows 2D examples. In MXNet, there is a recent merge to support 3D convolution using cudnn, does it work in MXNet.jl?

How about 3D deconvolution?

**Comment by pluskid** [comment]
All the operators added in MXNet should be automatically available from MXNet.jl. You will need to get the latest MXNet and re-compile.

**Comment by jingpengwu** [comment]
updated and recompiled. I see 3D convolution. The deconvolution seems only support 2D. Anyway, these belongs to the c++ core, close here.
