### ISSUE TITLE
ERROR: unrecognized keyword argument "n_epoch"

### ISSUE THREAD

**Issue by philtomson** [dmlc/MXNet.jl#12]
I was going through the mnist tutorial in the REPL and got to this line:

julia> mx.fit(model, optimizer, train_provider, n_epoch=20, eval_data=eval_provider)
ERROR: unrecognized keyword argument "n_epoch"

I had just upgraded to 0.0.3 and this is running on Julia 0.4

**Comment by pluskid** [comment]
Could you double check you are on 0.0.3? Or restart the repl? Because that error seems exactly due to an old version. If that still does not work, maybe could you try the got version?

**Comment by philtomson** [comment]
Ah, could be because I didn't restart the REPL. I'll try again when I get
back to my computer.

**Comment by pluskid** [comment]
closing. but feel free to reopen if issue still not resolvrd
