### ISSUE TITLE
Check out a specific tag or sha in deps/build.jl

### ISSUE THREAD

**Issue by tkelman** [dmlc/MXNet.jl#136]
Rather than always cloning latest master of the dependency library. Updating frequently is fine and expected, but one tagged version of the Julia package should correspond to exactly one specific, repeatable version of the dependency library. Otherwise installing version x.y.z of MXNet.jl today won't give the same result as installing it tomorrow, due to potential changes on master of the mxnet repo. Worst case, some breaking change in the upstream repo could suddenly break every existing tagged version of the Julia package. This is hopefully an unlikely situation, but easy to prevent.
ref https://github.com/JuliaLang/METADATA.jl/pull/6270#issuecomment-245002791 and https://github.com/dmlc/MXNet.jl/blob/ae1d45b4566114c1f271c07fdc36e5f3bd4824eb/deps/build.jl#L60

**Comment by pluskid** [comment]
Good suggestions. Now we still let the master branch to track libmxnet master. But when tagging releases, we switch to a `stable` branch and checkout a specific SHA of libmxnet.
