### ISSUE TITLE
ArrayDataProvider and array shapes

### ISSUE THREAD

**Issue by colbec** [dmlc/MXNet.jl#140]
Sorry, a very basic question. I am building a toy model using ArrayDataProvider and feeding a Julia array into it such as:
```
julia> data = [1 2 3 1; 2 3 4 0; 3 3 4 1; 5 3 4 2]
4×4 Array{Int64,2}:
 1  2  3  1
 2  3  4  0
 3  3  4  1
 5  3  4  2
```
In this array the features are the first 1:end-1 columns, and the last column is the label.
Now I think this is a pretty standard machine learning setup, so the code:
```
julia> mx.ArrayDataProvider(:dat => data[:,1:end-1],:lab => data[:,end])
ERROR: AssertionError: Number of samples in  lab is mismatch with dat
 in #ArrayDataProvider#871(::Int64, ::Bool, ::Int64, ::Int64, ::Type{T}, ::Pair{Symbol,Array{Int64,2}}, ::Pair{Symbol,Array{Int64,1}}) at /home/colin/.julia/v0.6/MXNet/src/io.jl:313
 in MXNet.mx.ArrayDataProvider(::Pair{Symbol,Array{Int64,2}}, ::Pair{Symbol,Array{Int64,1}}) at /home/colin/.julia/v0.6/MXNet/src/io.jl:269
```
comes as a surprise.
Oddly if I transpose the dat section then the provider is happy, but it leaves me puzzled why that would work and not the first version. I am missing a basic principle here, can anyone clarify?
Using MXNet 0.0.8+ master from checkout+build on Julia 0.6 on openSUSE Leap 42.1

**Comment by pluskid** [comment]
It's because of different convention. Each row is a sample or each column. Both paradigm exists in machine learning and statistics. In MXNet we follow the convention that each sample is a contiguous piece of memory, and since Julia is column-major matrix formatting, that means each column is a data sample. Hope this clarifies your question.

**Comment by niczky12** [comment]
This is very useful information. Is this highlighted somewhere in the tutorials? Others might benefit from knowing this fact.

**Comment by colbec** [comment]
Great, thanks.
