### ISSUE TITLE
Specifying the evaluation metric for regression

### ISSUE THREAD

**Issue by colbec** [dmlc/MXNet.jl#141]
I'm running a regression and want to fit() specifying MSE. There appears to be rmse available, but I am not sure how to get to it.
In `mx.fit(model, optimizer, mxd, n_epoch = 10,eval_metric=?)` without the eval_metric all runs well but with non-informative results since the metric is accuracy.
If I examine the contents of the MXNet.mx.* inventory of resources I was expecting to find a "metric" but nothing there. Next step?

**Comment by vchuravy** [comment]
See the documentation at http://dmlc.ml/MXNet.jl/latest/api/metric/ I think `mx.MSE` is what you want. Note that this will only influence the metric that is used to display statistics for you and not the metric that is used internally to train the model.

**Comment by colbec** [comment]
Got it, thanks, can't think how I did not see it.
