### ISSUE TITLE
Moving to a branch based support model for v0.4

### ISSUE THREAD

**Issue by vchuravy** [dmlc/MXNet.jl#152]
I would like to consider moving to a branch model where support for Julia v0.4 is on a separate branch.
This will allow us to use features from v0.5 and fix the remaining deprecation warnings.

**Comment by pluskid** [comment]
@vchuravy Since Julia v0.5 has been released for a while. I'm also OK to tag a new version of MXNet.jl (if there is any non-trivial changes since the last release) as the last one supporting Julia v0.4, and then update `REQUIRE` to Julia v0.5 in master.

**Comment by vchuravy** [comment]
Sounds good. I think there has been nothing breaking since the last
release. But we should also update to the current mxnet proper release (as
long as that doesn't require nnvm)
