### ISSUE TITLE
ERROR: InitError: ccall: could not find function MXSymbolGetAtomicSymbolName

### ISSUE THREAD

**Issue by apeano** [dmlc/MXNet.jl#157]
Hi,
the idea was to test MXNet.jl with the GPU functionalities on Windows 10.
I installed the latest stable mxnet dll with GPU support, here:
https://github.com/dmlc/mxnet/releases/download/20160531/20160531_win10_x64_gpu.7z
Then I built MXNet.jl and everything was OK.

When I load MXNet.jl I get this error:
ERROR: InitError: ccall: could not find function MXSymbolGetAtomicSymbolName

If I browse the dll's entry points I find only MXSymbolGetAtomicSymbolInfo, so I guess something changed in the library, or, I am using the wrong library.

I also tried the nighyly release, that actually has the required entry point, but in that case I get another error during the MXNet.jl building:
INFO: Building MXNet
INFO: MXNET_HOME environment detected: C:\Program Files\20161215_mxnet_x64_gpu
INFO: Trying to load existing libmxnet...
INFO: Failed to load existing libmxnet, trying to build from source...

Anyways... Using MXNet.jl with GPU support on Win 10 seems to be not straightforward.
Any ideas?

Thanks.

**Comment by vchuravy** [comment]
I am developing on Linux so I have not tested that setup. It might be worthwile setting up Appveyor for integration testing.

**Comment by pluskid** [comment]
I don't think Appveyor has GPU support. @apeano did you test if CPU only version works for you? Or both fails?

**Comment by apeano** [comment]
Hi, I am trying to test some other installations... However the setupenv.cmd is very annoying. It deletes parts of Path it should not... It cannot somehow update the MXNET_HOME variable.

Also even if I set the env vars by hand, rebuilding MXnet leaves a dirty environment.

**Comment by apeano** [comment]
Well, after a couple of attempts, the nightly CPU release is working.

**Comment by vchuravy** [comment]
@apeano that sounds like you solved your issue?
