### ISSUE TITLE
Tag a release for MXNet 0.9.3

### ISSUE THREAD

**Issue by vchuravy** [dmlc/MXNet.jl#183]
The latest release of MXNet.jl only supports 873b928 (2016.09.08) and we should release a new version for https://github.com/dmlc/mxnet/releases/tag/v0.9.3

Maybe we should consider using [AttoBot](https://discourse.julialang.org/t/attobot-a-package-release-bot/494?u=vchuravy) to make it easier to release versions of MXNet.jl?

**Comment by pluskid** [comment]
@vchuravy Yes, I completely agree. I may try to tag a new version within this week, but if you have some extra time, please go ahead and do it. [Here](https://github.com/dmlc/MXNet.jl/blob/master/README-DEV.md) are some steps that need to be taken care of during releasing a new version.

And AttoBot definitely looks interesting!

**Comment by vchuravy** [comment]
Will do can you set up AttoBot? Otherwise I will do a manual release.

**Comment by vchuravy** [comment]
X-Ref: https://github.com/JuliaLang/METADATA.jl/pull/7687

**Comment by pluskid** [comment]
Well I do not have admin permission for DMLC either, I will open an issue in the main repo.

**Comment by pluskid** [comment]
AttoBot should be configured: https://github.com/dmlc/mxnet/issues/4821

**Comment by vchuravy** [comment]
Thanks! `v0.2.0` is tagged in METADATA https://github.com/JuliaLang/METADATA.jl/pull/7700
