### ISSUE TITLE
Error while compiling MXNet CPU for windows 10

### ISSUE THREAD

**Issue by kishoreabhishek** [dmlc/MXNet.jl#185]
when i write - using MXNet on Julia prompt I get the following error
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x0 -- unknown function (ip: 0000000000000000)
while loading C:\Users\Abhishekta\.julia\v0.5\MXNet\src\ndarray.jl, in expression starting on line 1078
unknown function (ip: FFFFFFFFFFFFFFFF)
macro expansion at C:\Users\Abhishekta\.julia\v0.5\MXNet\src\base.jl:55 [inlined]
_get_libmx_op_names at C:\Users\Abhishekta\.julia\v0.5\MXNet\src\util.jl:69
unknown function (ip: 00000000075D03D6)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1942
@_import_ndarray_functions at C:\Users\Abhishekta\.julia\v0.5\MXNet\src\ndarray.jl:1057
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
fl_invoke_julia_macro at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\ast.c:161
apply_cl at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:1227
do_trycatch at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:899
apply_cl at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:1807
_applyn at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:683
fl_applyn at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/flisp\flisp.c:723
jl_parse_eval_all at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\ast.c:702
jl_load at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:596 [inlined]
jl_load_ at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:605
include_from_node1 at .\loading.jl:488
unknown function (ip: 0000000061C63D01)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1942
do_call at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:66
eval at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:190
jl_toplevel_eval_flex at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:558
jl_eval_module_expr at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:196
jl_toplevel_eval_flex at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:465
jl_eval_module_expr at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:196
jl_toplevel_eval_flex at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:465
jl_parse_eval_all at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\ast.c:717
jl_load at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:596 [inlined]
jl_load_ at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:605
include_from_node1 at .\loading.jl:488
unknown function (ip: 0000000061C63D01)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1942
do_call at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:66
eval at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:190
jl_toplevel_eval_flex at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:558 [inlined]
jl_toplevel_eval at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:580
jl_toplevel_eval_in_warn at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\builtins.c:590
macro expansion; at .\none:2 [inlined]
anonymous at .\<missing> (unknown line)
unknown function (ip: 00000000075706E6)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_toplevel_eval_flex at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:569 [inlined]
jl_toplevel_eval at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:580
jl_toplevel_eval_in_warn at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\builtins.c:590
eval at .\boot.jl:234
unknown function (ip: 0000000061C4D605)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1942
process_options at .\client.jl:239
_start at .\client.jl:318
unknown function (ip: 0000000061C8BEBE)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1942
jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/ui/../src\julia.h:1392 [inlined]
true_main at /home/Administrator/buildbot/slave/package_win6_2-x64/build/ui\repl.c:112
wmain at /home/Administrator/buildbot/slave/package_win6_2-x64/build/ui\repl.c:232
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-4.0.6-1/crt\crtexe.c:329
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-4.0.6-1/crt\crtexe.c:212
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 1427289 (Pool: 1426393; Big: 896); GC: 0
ERROR: Failed to precompile MXNet to C:\Users\Abhishekta\.julia\lib\v0.5\MXNet.ji.
 in compilecache(::String) at .\loading.jl:593
 in require(::Symbol) at .\loading.jl:422

**Comment by vchuravy** [comment]
Can you try the current master? #186 might have fixed this.

**Comment by kishoreabhishek** [comment]
Thanks for the reply. I started working on Julia 2 days back. Do you mean I should run PKG.update("MXNet")

**Comment by vchuravy** [comment]
Pkg.checkout("MXNet"); Pkg.update() should do the trick.

**Comment by kishoreabhishek** [comment]
julia> Pkg.checkout("MXNet");
INFO: Checking out MXNet master...
INFO: Pulling MXNet latest master...
INFO: No packages to install, update or remove

When I run Pkg.update()
INFO: Updating METADATA...
INFO: Updating MXNet master...
INFO: Computing changes...
INFO: No packages to install, update or remove

and the original error still persists

**Comment by kishoreabhishek** [comment]
I am getting the same error even if I try MXNet for Windows x64 GPU

**Comment by vchuravy** [comment]
You are missing a Pkg.build() to update the underlying MXNet package.

**Comment by vchuravy** [comment]
To expand on my previous point, this looks like you are using outdated binaries and during `Pkg.build()` we update those.

**Comment by kishoreabhishek** [comment]
I had downloaded the binaries from github. I deleted those binaries and did Pkg.build as instructed by you. That seems to have fixed the issue  Thanks for your help. One more question I expected that PKG.build would build the binaries in MXnet_home directory but could not find any there. But now using MXNet does not give any error.Why?

**Comment by vchuravy** [comment]
We take `MXNET_HOME` as a hint and check if there is a pre-installed version of MXNet, if we can't find a version we download the correct binaries and install them into `Pkg.dir("MXNet","deps")`.

Good to hear that it works now! I am in the process of releasing a new version with these changes.
