### ISSUE TITLE
https://github.com/dmlc/mxnet/blob/master/example/rnn/char_lstm.ipynb is broken

### ISSUE THREAD

**Issue by kishoreabhishek** [dmlc/MXNet.jl#198]
https://github.com/dmlc/mxnet/blob/master/example/rnn/char_lstm.ipynb is broken

**Comment by pluskid** [comment]
The fixes in #197 should fix it. I will try to make a patch soon.

**Comment by pluskid** [comment]
There seems to be some re-organizations in the examples since then. Closing this for now.
