### ISSUE TITLE
TODOs for v0.0.1

### ISSUE THREAD

**Issue by pluskid** [dmlc/MXNet.jl#2]
# APIs
* [x] `Context`
* [x] `NDArray`
  * [x] Creating and copying
  * [x] Elementwise arithmetics
* [x] `NameManager`
* [x] `Symbol`
  * [x] Creating, composing, grouping
  * [x] Shape inference
  * [x] Binding
* [x] `Executor`
* [x] `Initializer`
* [x] `DataProvider`
  * [x] Imported data iterator from `libmxnet`
* [x] `Optimizer`
* [x] `KVStore`
* [x] `Accuracy` Evaluation Metric
* [x] `Estimator`

# MISC
* [x] Documentation
  * [x] Setup RTD hooks
  * [x] Automatic extract docstring
  * [x] Setup instructions, introduction, tutorial
* [x] Testing
  * [x] Unit tests
  * [x] Set up Travis CI properly to compile `libmxnet.so` 
* [x] Examples
  * [x] MNIST MLP
  * [x] MNIST LeNet
  * [x] cifar10
* [x] BinDeps.jl automatically building MXNet binary.

**Comment by panlanfeng** [comment]
How about tell it build dependencies automatically using [BinDeps.jl](https://github.com/JuliaLang/BinDeps.jl)?

**Comment by antinucleon** [comment]
Previous in XGBoost.jl I am using BinDeps.jl

**Comment by pluskid** [comment]
Yes that could be nice. I have never worked with BinDeps.jl, do you think it is easy to build mxnet automatically via BinDeps.jl? I think mxnet itself needs some manual configuration to build as it depends on some 3rd party libraries like BLAS, OpenCV that could be provided in 1000 different way on different computer clusters. So users might still need to do some customization of the Makefile, etc. 

Another point is that the user might have a separate or existing installation of MXNet itself. Like in the Python or R case, the procedure is to download and install MXNet, compile it locally and then compile & install the Python / R package. Following the convention, the user might download and compile MXNet, and then install the Julia package (though from a different source tree).

What do you think? If BinDeps.jl is convenient enough to figure out the dependencies in the most case and maybe also skip building if existing MXNet installation is detected, then I think using BinDeps.jl might be very nice.

**Comment by panlanfeng** [comment]
BinDeps.jl provides `AptGet`, `Pacman`, `Yum`, `Homebrew`  interfaces. It is easy to install third party dependences and that is why it is named "BinDeps". 

And it can also run shell commands to build from source. In this case it can download and install under the package directory. I don't know if there is any way to detect user installations. 

The package is already great. Building dependencies automatically is a small feature making the package more usable and user friendly. It  is not a problem to have several copies of MXNet installed (at least for me). Even if auto build fails, the user can still have a chance to manually set it up.

**Comment by pluskid** [comment]
OK! Thanks that makes sense! I have added it to the TODO. I will have a look at BinDeps.jl after I worked out the documentation generation system. Meanwhile, it would be very great if either of you @panlanfeng @antinucleon with existing experience in BinDeps.jl have some time to help writing a `build.jl` for MXNet.jl.

Currently MXNet.jl just searches existing `libmxnet.so` in the library path or under `$MXNET_HOME/lib` if the environment variable `MXNET_HOME` is set.

**Comment by antinucleon** [comment]
@pluskid OK, I will take a look after figure out RNN bug

**Comment by panlanfeng** [comment]
I would love to help.

**Comment by pluskid** [comment]
@antinucleon @panlanfeng Thanks! Please create a WIP pull request or leave a message here whenever anyone of us find some time to start working on this to avoid duplicated efforts. Thanks again!

**Comment by pluskid** [comment]
If you guys have not started yet, I'm looking into BinDeps.jl now. :)

**Comment by antinucleon** [comment]
Sorry I didn't start yet :-(

**Comment by pluskid** [comment]
@antinucleon No problem, I'm looking at xgboost.jl's build.jl

**Comment by pluskid** [comment]
OK, I added a simple build.jl to compile a default libmxnet, without opencv and CUDA. It would probably be enough for people to play with. I tested locally it works fine on my mac. The automatic build fails on my server node because we have very weird blas path. Although the library is in the search path, there is no equivalence of `LD_LIBRARY_PATH` for includes, so the build fails.

**Comment by tqchen** [comment]
This is great! Thanks for the awesome job

**Comment by pluskid** [comment]
@tqchen seeing countless commits in dmlc repo everyday is really pushing me a lot ... :P
