### ISSUE TITLE
Extracting weights from trained network

### ISSUE THREAD

**Issue by pevnak** [dmlc/MXNet.jl#203]
Hello,
I would like to ask, if it is possible to extract weight from trained network defined through symbolic language. Something in the sense of all computer vision papers showing masks of first level of convolutional operators.

Thanks for the answer.
Tomas

**Comment by pluskid** [comment]
Hi, if you look at [save_checkpoint](https://github.com/dmlc/MXNet.jl/blob/master/src/model.jl#L585), you will see a way to access the trained weights and the correspondence.

**Comment by pevnak** [comment]
Thank you very much for your reply.
It works.
Tomas
