### ISSUE TITLE
Pkg.test() on Julia 0.5.0 fails

### ISSUE THREAD

**Issue by mdpradeep** [dmlc/MXNet.jl#204]
One of the tests fails because `http://data.dmlc.ml/mxnet/data/mnist.zip` is not available.  This is referenced from https://github.com/dmlc/MXNet.jl/blob/master/src/util.jl#L21. Should this be changed to `http://data.mxnet.io/mxnet/data/mnist.zip` ?

**Comment by pluskid** [comment]
Thanks! We fixed this in the master. The dmlc.ml DNS is indeed very unstable from time to time.
