### ISSUE TITLE
ArrayDataProvider returns TypeError

### ISSUE THREAD

**Issue by machiningcentre** [dmlc/MXNet.jl#205]
ArrayDataProvider returns TypeError when using Images.jl.
```
julia> using Images
julia> using MXNet
julia> X = rand(10,10);
julia> p = mx.ArrayDataProvider(X)
ERROR: TypeError: #ArrayDataProvider#6688: in new, expected Array{Array{Float32,N},1}, got Array{Array{Float32,N},1}
 in #ArrayDataProvider#6688(::Int64, ::Bool, ::Int64, ::Int64, ::Type{T}, ::Array{Float64,2}, ::Array{Any,1}) at ~/.julia/v0.5/MXNet/src/io.jl:351
 in (::Core.#kw#Type)(::Array{Any,1}, ::Type{MXNet.mx.ArrayDataProvider}, ::Array{Float64,2}, ::Array{Any,1}) at ./<missing>:0
 in MXNet.mx.ArrayDataProvider(::Array{Float64,2}) at ~/.julia/v0.5/MXNet/src/io.jl:277
```
There is no problem without Images.jl.
```
julia> using MXNet
julia> X = rand(10,10);
julia> p = mx.ArrayDataProvider(X)
MXNet.mx.ArrayDataProvider(Array{Float32,N}[
Float32[0.415866 0.112956 … 0837056 0.398794; 0.590402 0.334468 … 0515418 0.200105; … ; 0.3765410.337045 … 0.677437 0.31439; 0.761557 0.601104 … 0.7393450.0729888]],Symbol[:data],Array{Float32,N}[],Symbol[],10,10,false,0.0f0,0.0f0,MXNet.mx.NDArray[mx.NDArray{Float32}(10,10)],MXNet.mx.NDArray[])
```

Julia version and the package status are as follows:
```
julia> versioninfo()                                        
Julia Version 0.5.0                                         
Commit 3c9d753 (2016-09-19 18:14 UTC)                       
Platform Info:                                              
  System: Linux (x86_64-pc-linux-gnu)                       
  CPU: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz            
  WORD_SIZE: 64                                             
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_                                    
  LIBM: libopenlibm                                         
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)                     
                                                            
julia> Pkg.status("MXNet")                                  
 - MXNet                         0.2.1                      
                                                            
julia> Pkg.status("Images")                                 
 - Images                        0.7.0                      
```

**Comment by pluskid** [comment]
I can confirm this error. However, I do not understand the error message or why such an error is thrown out. Maybe we should open an issue in the Julia repo or Images.jl repo to see if anyone would know what is the issue here.

**Comment by AlejandroVera** [comment]
Hi. I'm having the same problem. Any news about it? Were you able to solve it?

**Comment by vchuravy** [comment]
What version of Julia are you using? What is you `Pkg.status()`? I noticed this as well and it might be related to https://github.com/JuliaLang/julia/issues/18465

cc: @timholy

**Comment by AlejandroVera** [comment]
Hi. My version and packages are the following: 
> Julia Version 0.5.0
> Commit 3c9d753 (2016-09-19 18:14 UTC)
> Platform Info:
>   System: Linux (x86_64-linux-gnu)
>   CPU: Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz
>   WORD_SIZE: 64
>   BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
>   LAPACK: liblapack.so.3
>   LIBM: libopenlibm
>   LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

> 17 required packages:
>  - ArrayFire                     0.0.4
>  - Feather                       0.2.5
>  - Gadfly                        0.6.0
>  - GraphViz                      0.1.0
>  - IJulia                        1.4.1
>  - ImageMagick                   0.2.3
>  - JLD                           0.6.10
>  - MXNet                         0.2.1
>  - MultivariateStats             0.3.1
>  - Plots                         0.10.3
>  - Query                         0.3.2
>  - RDatasets                     0.2.0
>  - Requests                      0.4.1
>  - StructuredQueries             0.0.4
>  - TensorFlow                    0.5.1
>  - XGBoost                       0.2.0
>  - ZipFile                       0.3.0
> 83 additional packages:
>  - AxisAlgorithms                0.1.6
>  - BinDeps                       0.4.7
>  - Blosc                         0.2.0
>  - BufferedStreams               0.3.2
>  - Calculus                      0.2.2
>  - CategoricalArrays             0.1.3
>  - Codecs                        0.3.0
>  - ColorTypes                    0.4.0
>  - Colors                        0.7.3
>  - Compat                        0.22.0
>  - Compose                       0.4.5
>  - Conda                         0.5.3
>  - Contour                       0.2.0
>  - DataArrays                    0.3.12
>  - DataFrames                    0.9.0
>  - DataStreams                   0.1.3
>  - DataStructures                0.5.3
>  - DiffBase                      0.1.0
>  - Distances                     0.4.1
>  - Distributions                 0.12.2
>  - DocStringExtensions           0.3.2
>  - Documenter                    0.9.2
>  - DualNumbers                   0.3.0
>  - FileIO                        0.3.1
>  - FixedPointNumbers             0.3.6
>  - FixedSizeArrays               0.2.5
>  - FlatBuffers                   0.2.0
>  - Formatting                    0.2.1
>  - ForwardDiff                   0.4.1
>  - FunctionWrappers              0.0.1
>  - GZip                          0.3.0
>  - Graphics                      0.2.0
>  - HDF5                          0.8.0
>  - Hexagons                      0.0.4
>  - Hiccup                        0.1.1
>  - HttpCommon                    0.2.7
>  - HttpParser                    0.2.0
>  - ImageCore                     0.2.1
>  - Interpolations                0.3.8
>  - Iterators                     0.3.0
>  - JSON                          0.8.3
>  - Juno                          0.2.7
>  - KernelDensity                 0.3.2
>  - LegacyStrings                 0.2.1
>  - Libz                          0.2.4
>  - LineSearches                  0.1.5
>  - Loess                         0.1.0
>  - MNIST                         0.0.2
>  - MacroTools                    0.3.6
>  - MappedArrays                  0.0.7
>  - MbedTLS                       0.4.5
>  - Measures                      0.0.3
>  - Media                         0.2.6
>  - NaNMath                       0.2.4
>  - NamedTuples                   1.0.0
>  - Nettle                        0.3.0
>  - NullableArrays                0.1.0
>  - OffsetArrays                  0.2.14
>  - Optim                         0.7.8
>  - PDMats                        0.5.6
>  - PlotThemes                    0.1.1
>  - PlotUtils                     0.3.0
>  - PositiveFactorizations        0.0.4
>  - ProtoBuf                      0.4.0
>  - PyCall                        1.11.1
>  - QuadGK                        0.1.2
>  - RData                         0.0.4
>  - Ratios                        0.0.4
>  - RecipesBase                   0.1.0
>  - Reexport                      0.0.3
>  - Requires                      0.3.0
>  - Rmath                         0.1.6
>  - SHA                           0.3.2
>  - ShowItLikeYouBuildIt          0.0.1
>  - Showoff                       0.0.7
>  - SortingAlgorithms             0.1.1
>  - SpecialFunctions              0.1.1
>  - StatsBase                     0.13.1
>  - StatsFuns                     0.4.0
>  - URIParser                     0.1.8
>  - WeakRefStrings                0.2.0
>  - WoodburyMatrices              0.2.2
>  - ZMQ                           0.4.2

**Comment by vchuravy** [comment]
I can confirm that this happens on 0.5.1. as well so it is unrelated to the issue I noted above.
