### ISSUE TITLE
"key "stride" not found" when using to_graphviz with Convolutional layers 

### ISSUE THREAD

**Issue by facundoq** [dmlc/MXNet.jl#213]
When using `to_graphviz` to print a network with a Convolutional layer, an KeyError  is thrown in `MXNet/src/visualize.jl:72` because the key "stride" does not exist in the Convolutional node.

Apparently the python api does the same thing:
https://github.com/dmlc/mxnet/blob/master/python/mxnet/visualization.py#L252

Printing the node you get:
```
Dict{String,Any}(Pair{String,Any}("name","convolution1"),Pair{String,Any}("attr",Dict{String,Any}(Pair{String,Any}("num_filter","64"),Pair{String,Any}("kernel","(5,5)"))),Pair{String,Any}("op","Convolution"),Pair{String,Any}("inputs",Any[Any[10,0,0],Any[11,0,0],Any[12,0,0]]))
```
Removing the stride info in https://github.com/dmlc/MXNet.jl/blob/master/src/visualize.jl#L72-L74 fixes the problem for me.

**Comment by pluskid** [comment]
Thanks! Since this seem to be a bug in the backend. Could you please open an issue in the main repo (and reference this one)?

**Comment by facundoq** [comment]
There's been no reply in the main repo, but apparently the python API checks if the key "stride" exists, and if not prints the stride as "1". I have a local commit that fixes this. Should I submit a PR?

**Comment by pluskid** [comment]
@facundoq Thanks! Submitting a PR should be great!
