### ISSUE TITLE
Metrics slow down training

### ISSUE THREAD

**Issue by vchuravy** [dmlc/MXNet.jl#222]
I noticed that every time I add an additional metric my training time increased by ~50s a batch.
```
INFO: ## Training summary
INFO:              ACE_1 = 0.6530
INFO:              ACE_2 = 0.6083
INFO:                ACE = 0.6427
INFO:                MSE = 134.2541
INFO:               time = 207.8117 seconds
```

Whereas training with a `NullMetric` that does nothing is blazing fast:
```
INFO: ## Training summary
INFO:               time = 59.7315 seconds
```

Even more noticeable if one switches to Power that has lower single-core performance.
@staticfloat do you have ideas on how we could quickly fix this? One idea is to calculate the metrics with `@threads`, 
but there should also be a way to not stall MXNet proper while we calculate the metrics.

**Comment by pluskid** [comment]
I think one reason might be the current implementation convert NDArray to Julia Array. And this create a sync point for the underlying async training process, therefore blocking the pipeline. What we might try to do is to implement the metrics using NDArray operators, allowing async engine to not blocking the process.

**Comment by vchuravy** [comment]
With `NullMetric` I still have to copy the output over:
https://github.com/dmlc/MXNet.jl/blob/c9eb71bc8bbc52c56dae097405caaf9985c99834/src/model.jl#L474

I think the problem is that we block on https://github.com/dmlc/MXNet.jl/blob/c9eb71bc8bbc52c56dae097405caaf9985c99834/src/model.jl#L520 instead of continuing the training.

**Comment by vchuravy** [comment]
Yeah putting a simple `@time` in front of that line:
Per batch: `4.578292 seconds (88.42 M allocations: 2.062 GB, 5.83% gc time)`
With `NullMetric` `0.00001 seconds`

**Comment by vchuravy** [comment]
With the improvements in https://github.com/dmlc/MXNet.jl/tree/vc/multi I brought down the runtime above from `207.8117 seconds` to `61.3162 seconds` with metrics (4 cores MT). I will see if I can refactor that a bit more and prepare a PR with it.

**Comment by pluskid** [comment]
Great! Thanks!

BTW: I think as long as the operation remains on mx.NDArray only, copying and computing will not block async operations because NDArray has a async execution engine by default. But copying to julia Arrays will block and wait until the actual data is available.

**Comment by albinsunesson** [comment]
I have a problem that I think is connected to this topic. Is it possible to compare the size of two numbers in NDArrays and receive a Boolean without copying over the numbers to CPU?

**Comment by pluskid** [comment]
@albinsunesson You can do pointwise comparison with NDArrays, except that the results are float NDArrays instead of boolean, because I don't think there is currently supports for boolean arrays on GPUs.
