### ISSUE TITLE
method error when using `.*` between identical symbols on 0.6

### ISSUE THREAD

**Issue by ExpandingMan** [dmlc/MXNet.jl#253]
The following error is thrown when doing, e.g. `x .* x` on 0.6:
```
MethodError: no method matching *(::MXNet.mx.NDArray, ::MXNet.mx.NDArray)
  Closest candidates are:
    *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:424
    *(::MXNet.mx.NDArray, !Matched::Real) at /Users/travis/.julia/v0.6/MXNet/src/ndarray.jl:642
    *(!Matched::Real, ::MXNet.mx.NDArray) at /Users/travis/.julia/v0.6/MXNet/src/ndarray.jl:646
```
This is because the method extension of `braodcast(*, ...)` gets bypassed in favor of the definition of `broadcast` in `Base` only in cases where the arguments to `.*` are identical symbols.  To see why, do `expand(:(x .* x))` and compare to `expand(:(x .* y))`.  There is ongoing [discussion](https://github.com/JuliaLang/julia/issues/22053) about whether this will remain the default behavior and how best to resolve it.

Note that, at least for the time being, Julia assumes that dotted operators necessarily imply some sort of loop over the operator on individual elements of a container.  Therefore, it might make more sense to use another, non-dotted operator such as `⊙` for Hadamard products in cases where there is no underlying Julia loop.

**Comment by iblis17** [comment]
found a workaround: `1x .* x`
