### ISSUE TITLE
Git error adding package

### ISSUE THREAD

**Issue by JosephBoyd** [dmlc/MXNet.jl#258]
I get the following error on Linux Mint 18 Cinammon

INFO: Installing Formatting v0.2.1
INFO: Installing MXNet v0.2.3
INFO: Building MXNet
INFO: Found a CUDA installation.
INFO: Attempting to Create directory /home/joe/.julia/v0.5/MXNet/deps/src
INFO: Directory /home/joe/.julia/v0.5/MXNet/deps/src already created
INFO: Attempting to Create directory /home/joe/.julia/v0.5/MXNet/deps/usr/lib
INFO: Directory /home/joe/.julia/v0.5/MXNet/deps/usr/lib already created
INFO: Attempting to Create directory /home/joe/.julia/v0.5/MXNet/deps/src/mxnet
INFO: Directory /home/joe/.julia/v0.5/MXNet/deps/src/mxnet already created
INFO: Changing Directory to /home/joe/.julia/v0.5/MXNet/deps/src/mxnet
INFO: Changing Directory to /home/joe/.julia/v0.5/MXNet/deps/src/mxnet
INFO: Changing Directory to /home/joe/.julia/v0.5/MXNet/deps/src/mxnet
M	cub
HEAD is now at 8713d25... [R][DOC] update R installation guide (#6457)
INFO: Changing Directory to /home/joe/.julia/v0.5/MXNet/deps/src/mxnet
fatal: reference is not a tree: 89de7ab20167909bc2c4f8acd397671c47cf3c0d
Unable to checkout '89de7ab20167909bc2c4f8acd397671c47cf3c0d' in submodule path 'cub'
=========================================================================================[ ERROR: MXNet ]==========================================================================================

LoadError: failed process: Process(`git submodule update --init`, ProcessExited(1)) [1]
while loading /home/joe/.julia/v0.5/MXNet/deps/build.jl, in expression starting on line 58

===================================================================================================================================================================================================

=========================================================================================[ BUILD ERRORS ]==========================================================================================

WARNING: MXNet had build errors.

 - packages with build errors remain installed in /home/joe/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("MXNet")`
 - build a single package by running its `deps/build.jl` script

===================================================================================================================================================================================================
INFO: Package database updated

**Comment by joshbode** [comment]
Looks like the latest tag (v0.10.0) of upstream used in the build (dmlc/mxnet@8713d25) is referencing a commit in a submodule (NVlabs/cub@89de7ab) that is "unadvertised", whatever that means.

```bash
$ git clone --recursive https://github.com/dmlc/mxnet
$ cd mxnet
$ git submodule update --init
error: Server does not allow request for unadvertised object 89de7ab20167909bc2c4f8acd397671c47cf3c0d
Fetched in submodule path 'cub', but it did not contain 89de7ab20167909bc2c4f8acd397671c47cf3c0d. Direct fetching of that commit failed.
```

**Comment by pluskid** [comment]
Yes, this is a somehow "known" issue that NVidia did something weird to their cub package and breaks the submodule. I was able get it to work by deleting everything related to cub in .git config and refs and re-do the submodule. Doing a fresh clone of mxnet should also work. But it seems it is not working for you as shown above?

**Comment by JosephBoyd** [comment]
A fresh clone of mxnet did not work, but a fresh clone of cub did. Thank you gentlemen
