### ISSUE TITLE
How to build with openblas

### ISSUE THREAD

**Issue by VikingMew** [dmlc/MXNet.jl#26]
Can I do that?

**Comment by pluskid** [comment]
Yes, see [the doc](http://mxnetjl.readthedocs.org/en/latest/user-guide/install.html#manual-compilation) on how to make a custom build.

**Comment by VikingMew** [comment]
Thanks, I succeed with the guide.
But I cannot run the example on MLP. It is said that undefined mx.MLP.
Is that related to my custom build?

**Comment by pluskid** [comment]
The example in the homepage is for latest got version. You need to do Pkg.checkout("MXNet") to run those. Otherwise you can run the locally installed example instead of online version.
