### ISSUE TITLE
Documenter auto-deploy failed

### ISSUE THREAD

**Issue by iblis17** [dmlc/MXNet.jl#266]
from the recent passed build: 
 https://travis-ci.org/dmlc/MXNet.jl/jobs/237379828#L1573-L1576

and for reference: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#SSH-Deploy-Keys-1

**Comment by vchuravy** [comment]
I think only @pluskid has the right permissions to change that

**Comment by pluskid** [comment]
Went through the configuration steps. Should be fixed now. Please let me know if the issue persists.

**Comment by vchuravy** [comment]
Thanks!
