### ISSUE TITLE
auto importing of Symbloic Node function

### ISSUE THREAD

**Issue by iblis17** [dmlc/MXNet.jl#278]
The auto-imported function is using `MXSymbolCreateAtomicSymbol`.
https://github.com/dmlc/MXNet.jl/blob/2c5120d139fdd259f2d1b161ec94eea323d0fc20/src/symbolic-node.jl#L689-L696

But the function names and underlying c pointers are from ` MXListAllOpNames` and `NNGetOpHandle` , instead of `MXSymbolListAtomicSymbolCreators`. Will this be a problem?
https://github.com/dmlc/MXNet.jl/blob/2c5120d139fdd259f2d1b161ec94eea323d0fc20/src/util.jl#L65-L78

**Comment by pluskid** [comment]
I think it shouldn't be a problem. According to the [code](https://github.com/apache/incubator-mxnet/blob/master/src/c_api/c_api_symbolic.cc#L73), it seems list symbolic creators return unique creators, while list op names return all names including aliased operators.

**Comment by iblis17** [comment]
👌
