### ISSUE TITLE
prevent user from creating non-Float32 NDArray?

### ISSUE THREAD

**Issue by iblis17** [dmlc/MXNet.jl#284]
is this legit?
```julia
julia> mx.NDArray([1 2; 3 4])
mx.NDArray{Int64}(2, 2)
```

**Comment by iblis17** [comment]
https://github.com/apache/incubator-mxnet/blob/470b56437290b33fef51b067c96fdce08cefa584/include/mxnet/c_api.h#L277

seems legit

**Comment by vchuravy** [comment]
Yeah that is absolutely fine. I don't recall from the top of my head if we
are actually doing type inference over the entire graph yet, so that you
can mix datatypes.

**Comment by iblis17** [comment]
I'm working on porting autograd, when I issue gradient computation API with `NDArray{Int64}` array. It crashed 😂  
```julia
julia> [19:51:02] /home/iblis/.julia/v0.5/MXNet/deps/src/mxnet/dmlc-core/include/dmlc/./logging.h:308: [19:51$
02] include/mxnet/././tensor_blob.h:216: Check failed: mshadow::DataType<DType>::kFlag == type_flag_ TBlob.ge$
_with_shape: data type do not match specified type.Expected: 6 v.s. given 0
```

**Comment by vchuravy** [comment]
Yeah. Can you reproduce that issue in python?

**Comment by iblis17** [comment]
:-o Python works without crashing, though the output is insane.
