### ISSUE TITLE
mlp.jl: accept external arguments?

### ISSUE THREAD

**Issue by mcreel** [dmlc/MXNet.jl#298]
When using the neural net factory, 
 `mx.MLP([20, 10, 6])`
works fine to set up part of a chain. However, I would like to include this into a more general function that sets up a net taking the number of layers and the neurons per layer as arguments. That is, I would like to be able to use something like
 `mx.MLP(netconfig)`
where netconfig is previously defined to be `netconfig=[20, 10, 6]` or some other description which can easily be passed as an argument. 

This sort of thing used to work, before the changes that were done to get MXNet.jl working with julia 0.6.x. I haven't figured out how to do it with the current master version. Any help would be appreciated.

**Comment by iblis17** [comment]
well, this works for me. It's 3 layers, each layer's width is 20, 10 and 6
```julia
julia> mx.MLP(mx.Variable(:x), [20, 10, 6])                                                                                               MXNet.mx.SymbolicNode(MXNet.mx.MX_SymbolHandle(Ptr{Void} @0x0000558526226120))
       
julia> print(ans)         
Symbol Outputs:
        output[0]=##662fc3(0)
Variable:x              
Variable:##662fc1_weight
Variable:##662fc1_bias
--------------------            
Op:FullyConnected, Name=##662fc1
Inputs:                     
        arg[0]=x(0) version=0              
        arg[1]=##662fc1_weight(0) version=0
        arg[2]=##662fc1_bias(0) version=0
Attrs:               
        num_hidden=20
--------------------          
Op:Activation, Name=##662relu1
Inputs:                   
        arg[0]=##662fc1(0)
Attrs:
        act_type=relu
Variable:##662fc2_weight
Variable:##662fc2_bias
--------------------
Op:FullyConnected, Name=##662fc2
Inputs:
        arg[0]=##662relu1(0)
        arg[1]=##662fc2_weight(0) version=0
        arg[2]=##662fc2_bias(0) version=0
Attrs:
        num_hidden=10
--------------------
Op:Activation, Name=##662relu2
Inputs:
        arg[0]=##662fc2(0)
Attrs:
        act_type=relu
Variable:##662fc3_weight
Variable:##662fc3_bias
--------------------
Op:FullyConnected, Name=##662fc3
Inputs:
        arg[0]=##662relu2(0)
        arg[1]=##662fc3_weight(0) version=0
        arg[2]=##662fc3_bias(0) version=0
Attrs:
        num_hidden=6
```

**Comment by iblis17** [comment]
> However, I would like to include this into a more general function that sets up a net taking the number of layers and the neurons per layer as arguments.

hmm. I do not get this. I think the arg `[20, 10, 6]` is quite self-described already.

**Comment by mcreel** [comment]
Thanks. What I'm trying to do is to modify
`      net  = @mx.chain mx.Variable(:data) =>
        mx.MLP([20,10,6]) =>
        mx.LinearRegressionOutput(mx.Variable(:label))
`
to be 

`    layerconfig = [20,10,6]
    net  = @mx.chain mx.Variable(:data) =>
        mx.MLP(layerconfig) =>
        mx.LinearRegressionOutput(mx.Variable(:label))
`

or something similar, to have the layer configuration passed in as an argument. This does not work as written above, as it says "layerconfig not defined".

**Comment by iblis17** [comment]
oh, I got it. will send a PR

**Comment by iblis17** [comment]
please checkout #299 :)

**Comment by mcreel** [comment]
Thanks! I will try that out tomorrow.
