### ISSUE TITLE
Bilinear initializer

### ISSUE THREAD

**Issue by vchuravy** [dmlc/MXNet.jl#31]
Similar to https://github.com/BVLC/caffe/blob/603cbfb97767d1b9ebf102200646f5df237d1749/include/caffe/filler.hpp#L210-L262 it would be nice to have such an initializer in MXNet.jl

--- This is mostly for me to remember to implement this, but if anybody beats me to it go ahead.

**Comment by vchuravy** [comment]
@pluskid I would like to specify initializers per layer. What would be the best way to attach initializers to each Layer?

**Comment by pluskid** [comment]
Currently there is no way to attach extra information to a layer or operator. There were some discussion about adding general "attribute" to operators but we have not yet implemented yet. 

A most straightforward hack is to write a customized initializer that allow user to specify the initialization for matched layer name. This should be straightforward as the layer name is passed to initializer, one can store a dictionary or something, for example. And fallback to default initializer when no matching specification is found.

A more complicated way is to implement attribute on the Julia side. And the most complicated way is to implement it in libmxnet cpp side.
