### ISSUE TITLE
New Broadcast API in 0.7

### ISSUE THREAD

**Issue by iblis17** [dmlc/MXNet.jl#348]
Just file a TODO here.
https://github.com/JuliaLang/julia/pull/23939

**Comment by timholy** [comment]
Easiest to wait until https://docs.julialang.org/en/latest/manual/interfaces/#Interfaces-1 gets populated with the documentation for the new API (there will be a "Broadcasting" section).

**Comment by iblis17** [comment]
oh, nice. doc got rendered https://docs.julialang.org/en/latest/manual/interfaces/#man-interfaces-broadcasting-1

**Comment by iblis17** [comment]
fixed via https://github.com/apache/incubator-mxnet/pull/12845
