### ISSUE TITLE
Label for LogisticRegression

### ISSUE THREAD

**Issue by vchuravy** [dmlc/MXNet.jl#38]
Given a regression network like this:
````julia  
data = mx.Variable(:data)
  label = mx.Variable(:label)

   conv = @mx.chain mx.Convolution(data=data, kernel=(3,3), pad=(1,1), 64)  =>
                     mx.Activation(act_type=:relu) =>
                     mx.Convolution(kernel=(3,3), pad=(1,1), num_filter=128)  =>
                     mx.Activation(act_type=:relu) =>
                     mx.Pooling(pool_type=:max, kernel=(2,2), stride=(2,2))

   fc = @mx.chain mx.FullyConnected(data=conv, num_hidden=1) =>
                       mx.Activation(act_type=:sigmoid)
   net = mx.LogisticRegressionOutput(data=fc, label=label)
````

I have to specify the label data twice in `ArrayDataProvider` to be able to  provide for `LogisticRegressions(label=` and to satisfy the requirement for `Metric`.

````julia
mx.ArrayDataProvider((:data => data, :label => labels), :label => labels)
````

A possible fix for this might be that Variables could also be filled by inputs in the label vector of an ArrayDataProvider.

**Comment by pluskid** [comment]
I don't understand. Can you explain a bit why do you need to do that?

**Comment by pluskid** [comment]
Do you mean data it self is not enough for shape inference?

**Comment by kasiabozek** [comment]
Actually the problem arises when you need to have more than 1 regression outputs in your network.  
```julia
mx.ArrayDataProvider(:data => data, :label1 => labels1, :label2 => labels2)
```
is not possible and 
```julia
mx.ArrayDataProvider((:data => data, :label1 => labels1, :label2 => labels2), (:label1 => labels1, :label2 => labels2))
```
is one way to provide multiple labels into the network.

**Comment by vchuravy** [comment]
Sorry for not being more precise. 

As far as I understand it `*RegressionOutput` needs a `SymbolicNode` as label. (Which is different from how SoftmaxOutput works). In order to provide the `*RegressionOutput` the label data you have to create a `Variable` (see my example up top).

`Variables` are filled from the the first parameter in an `ArrayDataProvider` and thus `ArrayDataProvider((:data => data, :label => label))` fills the two defined `Variable`s. This works fine for most part, but in `Metric` https://github.com/dmlc/MXNet.jl/blob/master/src/metric.jl#L100 it is expected that the second parameter in `ArrayDataProvider` (`labels`) has the same length as the output of the network. So we have to use `:label => label` twice in `ArrayDataProvider`. 

My suggestion would be that we also use the `labels` from `ArrayDataProvider` to fill `Variable` slots in the network.

**Comment by vchuravy** [comment]
Sorry for the noise, I seemed to have tested the wrong combination. Everything works as I was thinking it should...

**Comment by pluskid** [comment]
@kasiabozek I believe this should work
```julia
mx.ArrayDataProvider(:data => data, (:label1 => labels1, :label2 => labels2))
```
or at least should be the expected behavior. If it does not work this way, it is a bug that we should fix.
