### ISSUE TITLE
@defstruct macro

### ISSUE THREAD

**Issue by Evizero** [dmlc/MXNet.jl#40]
I really like your `@defstruct` macro. Don't you think this would be nice as a small package called `SimpleStructs.jl`? I would use it all the time

**Comment by pluskid** [comment]
@Evizero Thanks for the suggestion! I googled a bit and there is already a package called [NamedTuple.jl](https://github.com/blackrock/NamedTuples.jl). It seems to be of a different flavor. I could definitely try to make the `@defstruct` macro a separate package if namedtuple.jl does not satisfy your need.

**Comment by Evizero** [comment]
I have seen that package, but it's not really the use case I have. I mostly have use cases similar to yours, in which I defines types to contain strongly typed hyper variables which are specified using weakly typed keyword arguments that have sensible defaults and some constraints.

The only thing that is missing for me in your macro is a way to make the type immutable, but I think that should be an easy addition that I could think about

**Comment by Evizero** [comment]
Forgive my bluntness. What I mean to say is that I would be grateful if you would put that code into its own package.

**Comment by pluskid** [comment]
I see, I will make some polishing and make it a separate small package soon. It was defining `immutable` types in the original code in Mocha.jl but I changed it when porting to MXNet.jl. I guess it should be easy to define variants.

**Comment by pluskid** [comment]
@Evizero See https://github.com/pluskid/SimpleStructs.jl

I made some improvements:
* immutable type is allowed by using `@defimmutable`
* required fields are allowed (omitting the default value will make the field *required*)
* super type can be specified by the syntax `StructName <: SuperType`

**Comment by Evizero** [comment]
awesome. thanks

**Comment by mauro3** [comment]
See also https://github.com/mauro3/Parameters.jl

**Comment by pluskid** [comment]
And see also the discussions here: JuliaLang/METADATA.jl#4114
