### ISSUE TITLE
Trouble using compiled mxnet

### ISSUE THREAD

**Issue by chrisdubois** [dmlc/MXNet.jl#41]
I successfully built mxnet with `USE_CUDA=1` in `~/mxnet`, running several examples with the Python client. I tried to follow the MXNet.jl build instructions to have the package use the `libmxnet.so` by setting MXNET_HOME='/home/chris/mxnet', starting julia, and running `Pkg.add("MXNet")`. I get the following

```
INFO: Building MXNet
INFO: MXNET_HOME environment detected: /home/chris/mxnet
INFO: Trying to load existing libmxnet...
INFO: Failed to load existing libmxnet, trying to build from source...
```

In `~/.julia/v0.4/MXNet/deps/build.jl` it looks like it uses $MXNET_HOME/lib/libmxnet.so during build so I think the above *should* work.

Any ideas on how to debug this?

**Comment by doobwa** [comment]
My apologies: it could find mxnet, but it couldn't find cuda, and it worked after doing `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64`. Please close this issue when you get a chance.
