### ISSUE TITLE
CUDA is required or this error is from other problem ?

### ISSUE THREAD

**Issue by programistawpf** [dmlc/MXNet.jl#420]
CUDA is required or this error is from other problem ?
Win7
 Version 0.6.2 (2017-12-13 18:08 UTC)
 x86_64-w64-mingw32

julia> Pkg.build("MXNet")
INFO: Building MXNet
INFO: Found a CUDA installation.
INFO: CUDA_HOME -> nothing
INFO: Downloading pre-built packages for Windows.
Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.SecurityProtocolType" due to invalid enu
meration values. Specify one of the following enumeration values and try again. The possible enumeration values are "Ss
l3, Tls"."
At line:1 char:28
+ [Net.ServicePointManager]:: <<<< SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (new-object net.webclient).Dow
nloadFile("https://github.com/yajiedesign/mxnet/releases/download/20171019/20171019_mxnet_x64_vc14_gpu.7z", "mxnet.7z")
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception calling "DownloadFile" with "2" argument(s): "Połączenie podstawowe zostało zakończone: Wystąpił nieoczekiwan
y błąd przy wysyłaniu."
At line:1 char:121
+ [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (new-object net.webclient).DownloadF
ile <<<< ("https://github.com/yajiedesign/mxnet/releases/download/20171019/20171019_mxnet_x64_vc14_gpu.7z", "mxnet.7z")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

====================================================[ ERROR: MXNet ]====================================================

LoadError: failed process: Process(`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell' -NoProfile -Command '[Net.Se
rvicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (new-object net.webclient).DownloadFile("https
://github.com/yajiedesign/mxnet/releases/download/20171019/20171019_mxnet_x64_vc14_gpu.7z", "mxnet.7z")'`, ProcessExited
(1)) [1]
while loading C:\Users\PC\.julia\v0.6\MXNet\deps\build.jl, in expression starting on line 81

========================================================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: MXNet had build errors.

 - packages with build errors remain installed in C:\Users\PC\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("MXNet")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================

julia> using MXNet
INFO: Precompiling module MXNet.
ERROR: LoadError: LoadError: Cannot find or load libmxnet.dll. Please see the document on how to build it.
Stacktrace:
 [1] error(::String) at .\error.jl:21
 [2] include_from_node1(::String) at .\loading.jl:576
 [3] include(::String) at .\sysimg.jl:14
 [4] include_from_node1(::String) at .\loading.jl:576
 [5] include(::String) at .\sysimg.jl:14
 [6] anonymous at .\<missing>:2
while loading C:\Users\PC\.julia\v0.6\MXNet\src\base.jl, in expression starting on line 38
while loading C:\Users\PC\.julia\v0.6\MXNet\src\MXNet.jl, in expression starting on line 25
ERROR: Failed to precompile MXNet to C:\Users\PC\.julia\lib\v0.6\MXNet.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:710
 [2] _require(::Symbol) at .\loading.jl:497
 [3] require(::Symbol) at .\loading.jl:405

Paul

**Comment by iblis17** [comment]
Hi, CUDA is optional.
It seems a download issue.
