### ISSUE TITLE
build error on ubuntu: ERROR: LoadError: UndefVarError: info not defined

### ISSUE THREAD

**Issue by scotthuang1989** [dmlc/MXNet.jl#427]
I try to build Mxnet, but following error pop up:

```
julia> Pkg.build("MXNet")
  Building MXNet → `~/.julia/packages/MXNet/i7RgE/deps/build.log`
┌ Error: Error building `MXNet`: 
│ ERROR: LoadError: UndefVarError: info not defined
│ Stacktrace:
│  [1] top-level scope at /home/scott/.julia/packages/MXNet/i7RgE/deps/build.jl:12
│  [2] include at ./boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1038
│  [4] include(::Module, ::String) at ./sysimg.jl:29
│  [5] include(::String) at ./client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at /home/scott/.julia/packages/MXNet/i7RgE/deps/build.jl:11
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Op
erations.jl:1068```
any one know what's missing? the error message don't tell me too much inofrmation.

**Comment by iblis17** [comment]
well, sorry that julia v1.0 is not supported yet.

**Comment by scotthuang1989** [comment]
I change to julia v0.7.0, different error pop up. Here is the output of **Pkg.add**  and **Pkg.resolve** 

> julia> Pkg.add("MXNet")
> WARNING: Base.Pkg is deprecated, run `using Pkg` instead
>  in module Main
>   Updating registry at `~/.julia/registries/General`
>   Updating git-repo `https://github.com/JuliaRegistries/General.git`
>  Resolving package versions...
>   Updating `~/.julia/environments/v0.7/Project.toml`
>  [no changes]
>   Updating `~/.julia/environments/v0.7/Manifest.toml`
>  [no changes]
> 
> julia> using MXNet
> [ Info: Precompiling MXNet [a7949054-b901-59c6-b8e3-7238c29bf7f0]
> ERROR: LoadError: ArgumentError: Package MXNet does not have Compat in its dependencies:
> - If you have MXNet checked out for development and have
>   added Compat as a dependency but haven't updated your primary
>   environment's manifest file, try `Pkg.resolve()`.
> - Otherwise you may need to report an issue with MXNet
> Stacktrace:
>  [1] require(::Module, ::Symbol) at ./loading.jl:830
>  [2] include at ./boot.jl:317 [inlined]
>  [3] include_relative(::Module, ::String) at ./loading.jl:1038
>  [4] include(::Module, ::String) at ./sysimg.jl:29
>  [5] top-level scope at none:2
>  [6] eval at ./boot.jl:319 [inlined]
>  [7] eval(::Expr) at ./client.jl:399
>  [8] top-level scope at ./none:3
> in expression starting at /home/scott/.julia/packages/MXNet/i7RgE/src/MXNet.jl:10
> ERROR: Failed to precompile MXNet [a7949054-b901-59c6-b8e3-7238c29bf7f0] to /home/scott/.julia/compiled/v0.7/MXNet/Sc0jU.ji.
> Stacktrace:
>  [1] error(::String) at ./error.jl:33
>  [2] macro expansion at ./logging.jl:313 [inlined]
>  [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1185
>  [4] _require(::Base.PkgId) at ./logging.jl:311
>  [5] require(::Base.PkgId) at ./loading.jl:852
>  [6] macro expansion at ./logging.jl:311 [inlined]
>  [7] require(::Module, ::Symbol) at ./loading.jl:834
>

**Comment by iblis17** [comment]
Well, it's not ready for 0.7/1.0; currently it is 0.6 only.
There are huge changes in 0.7/1.0, like broadcasting, stdlib, and Pkg system.

**Comment by scotthuang1989** [comment]
I will try it. do you think it's a good idea to put the supported version of julia in the release note?

**Comment by iblis17** [comment]
yeah, I can add it.
FYI, we are struggling in merging this repo into the main mxnet repo.
(see https://github.com/apache/incubator-mxnet/pull/10149)
And this repo will be deprecated in the near future.

**Comment by scotthuang1989** [comment]
Is there a plan for julia support on mxnet?

**Comment by iblis17** [comment]
Yes, just moving the development from here to the main mxnet repo.
And we want to integrate the CI validation chain like other language binding, e.g. Python, R... etc.

**Comment by scotthuang1989** [comment]
thanks very much. It seems a very interesting project.
