### ISSUE TITLE
Accuracy stats

### ISSUE THREAD

**Issue by kasiabozek** [dmlc/MXNet.jl#49]
How could one access accuracy of training in each epoch? Could metric be added to callback type? Maybe I'm missing it but I don't see how to register the training progress.

**Comment by vchuravy** [comment]
We could add a callback function to the metric, that provides the user with the callback value per epoch.

**Comment by pluskid** [comment]
yes since evaluation metric is call every epoch, we should add the computed information to the callback parameters of epoch callback!

**Comment by pluskid** [comment]
Closing coz added in a recent PR.

**Comment by GunnarFarneback** [comment]
This is useful but I would find it even more useful if the validation accuracy was also available through the callback. It doesn't look hard to add but it's less obvious how to design it. Adding another callback parameter or package training and validation metrics inside a Dict come to mind. Any opinions?
