### ISSUE TITLE
Accessing gradients directly

### ISSUE THREAD

**Issue by lqh20** [dmlc/MXNet.jl#5]
This project looks great! I'm interesting in accessing the gradients from backpropagation directly rather than using the estimator/optimizer/fit set up but I can't work out how. Any pointers?

**Comment by pluskid** [comment]
@lqh20 Yes. You can use `bind` or `simple_bind` to setup an `Executor`. `executor.grad_arrays` will contain all the gradient after you run the backward. To get the correspondence, match that with `list_arguments(executor)`.

**Comment by lqh20** [comment]
Great, thanks!
