### ISSUE TITLE
MXNet on julia 0.4.2

### ISSUE THREAD

**Issue by BigEpsilon** [dmlc/MXNet.jl#51]
Hi,

I'm trying to use MXNet for the first time and after installing successfuly on julia 0.4.2, ubuntu 14.04 x64, when I try (in IJulia)  the minst example (the one on the front page) I get this error:

    INFO: Start training on [GPU0]

    LoadError: MethodError: `_compose!` has no method matching _compose!(::MXNet.mx.SymbolicNode, ::Symbol, ::Type{Int64}, ::Float64)
    Closest candidates are:
      _compose!(::MXNet.mx.SymbolicNode, ::Union{Ptr{UInt8},Symbol}, !Matched::MXNet.mx.SymbolicNode...)
      _compose!(::MXNet.mx.SymbolicNode)
      _compose!(::MXNet.mx.SymbolicNode, !Matched::MXNet.mx.SymbolicNode...)
    while loading In[6], in expression starting on line 1

When I try to run any of the examples I get the following error:

    INFO: Start training on [GPU0]
    ERROR: LoadError: MethodError: `sum` has no method matching sum(::Array{Int64,1})
    you may have intended to import Base.sum
     in _split_inputs at /home/NOTME/.julia/v0.4/MXNet/src/model.jl:46
     in fit at /home/NOTYOU/.julia/v0.4/MXNet/src/model.jl:330
     in include at ./boot.jl:261
     in include_from_node1 at ./loading.jl:304
     in process_options at ./client.jl:280
     in _start at ./client.jl:378
    while loading /home/NOBODY/.julia/v0.4/MXNet/examples/mnist/lenet.jl, in expression starting on line 45

**Changing "sum" to "Base.sum" at line 46 of model.jl solves the problem.**

I never made a pull request on github so I'll try to do it here if this is relevant.

Thanks !

**Comment by pluskid** [comment]
Thanks for reporting this. I guess this is already fixed by your pull request?

**Comment by BigEpsilon** [comment]
Yes the pull request solve it for me. I'll close the issue as it was merged. 

Thanks to you.

**Comment by GunnarFarneback** [comment]
I'm curious what changed in Julia 0.4.2 to cause this to break but regardless it would be good to have a new release of MXNet.jl so it can be used out of the box with 0.4.2.

**Comment by pluskid** [comment]
agreed. will do it today.

**Comment by pluskid** [comment]
JuliaLang/METADATA.jl#4220
