### ISSUE TITLE
Getting MXNet.jl building on PackageEvaluator

### ISSUE THREAD

**Issue by IainNZ** [dmlc/MXNet.jl#54]
I noticed MXNet is failing to build on the PackageEvaluator machine:

http://pkg.julialang.org/logs/MXNet_0.4.log

The "machine" is actually a standard Ubuntu VM. It looks like its looking for CBLAS, which I guess isn't installed by default. Is it possible to get it to use OpenBLAS instead?

**Comment by pluskid** [comment]
On Ubuntu the building script will try to install libblas-dev using bindeps.jl. It is working properly for Travis ci, so kind of strange that building failed for package eval machine. 

We could use open las by changing the make file to point to openblas. Is openblas installed by default on packager machine? I'm also wondering, since Julia includes BLAS, can we use the built in BLAS directly? (Is the header files available somewhere?)

**Comment by IainNZ** [comment]
Looks like maybe that isn't enough, even on Travis it required https://github.com/dmlc/MXNet.jl/pull/17 to manually install CBLAS.

I think it might be possible to use the Julia OpenBLAS - @tkelman, do you know the logistics of that?

**Comment by pluskid** [comment]
Hmm, I think you are right. I forgot we had extra script to be executed for Travis. It would be great to be able to use Julia 's openblas though, as it will make automatic building much easier. I think it would not be hard if Julia ships with the complete lib files **and** header files for openblas.

**Comment by tkelman** [comment]
Are you sure you need the header files? Julia generally doesn't ship dependency headers, but for BLAS especially the prototypes are all standard. Though Julia's openblas is built as ILP64 most places (anywhere except linux distribution packages or homebrew) which you need to keep an eye out for. SCS.jl, or maybe Elemental.jl, are the current best examples of package dependencies linking against Julia's copy of openblas.

**Comment by pluskid** [comment]
@tkelman Thanks! The header file is actually needed because `libmxnet` needs to be built.

**Comment by tkelman** [comment]
How many routines are you calling? Declaring the prototypes locally for the routines you need would remove the need for having the header installed, and is what a lot of projects do.

**Comment by pluskid** [comment]
@tkelman That sounds a little bit scary to me. Although in principle all BLAS implementations should have the same interface, using a local self-crafted header file might be a potential source for difficult-to-find bugs. I guess I will just go with external BLAS.

@IainNZ How is the building process on the packager server triggered? Is there any way to debug (e.g. explicitly trigger the building)? Does the VM has sudo permission -- i.e. would the Apt source in BinDeps.jl work? Thanks!

**Comment by pluskid** [comment]
@IainNZ BTW: there is a bug in the Julia package list website: if you click the badge of any project, it redirect to the url http://pkg.julialang.org/?pkg=MXNet#MXNe -- always with the last letter missing, for any project I have tried.

**Comment by IainNZ** [comment]
@pluskid the full run is manually triggered by me right now. It uses the tagged version of a package, and installs it completely normally, with a `Pkg.add()`. The user does have `sudo` permission, and packages that use `apt` work great on the VM.

I can't recreate that! What browser?

**Comment by pluskid** [comment]
@IainNZ The original URL is, for example, http://pkg.julialang.org/?pkg=MXNet , when I open it (in both Chrome and Safari under OS X), it jumps to http://pkg.julialang.org/?pkg=MXNet#MXNe (notice the tailing `t` is missing). The same thing happens for other packages.

**Comment by IainNZ** [comment]
Ah, I see! I was trying an old URL with `&ver=0.3` in there too and it didn't happen. Will fix.

**Comment by vchuravy** [comment]
@IainNZ this should be working now. Could you test again?

**Comment by tkelman** [comment]
it's been hitting a download failure http://pkg.julialang.org/detail/MXNet.html
