### ISSUE TITLE
R-package lr_scheluder, clip_gradient and xavier initializer

### ISSUE THREAD

**Issue by Gelu74** [dmlc/MXNet.jl#57]
I am trying to port a model from python to R, basically the model call in python is:
model = mx.model.FeedForward(
        ctx                = dev,
        symbol             = net,
        num_epoch          = 35,
        learning_rate      = 0.01,
        momentum           = 0.9,
        wd                 = 0.0001,
        clip_gradient      = 5,
        lr_scheduler       = mx.lr_scheduler.FactorScheduler(step=epoch_size * lr_factor_epoch, factor = 0.1),
        initializer        = mx.init.Xavier(factor_type="in", magnitude=2.34))

but I can't find in R the equivalents for   lr_scheduler (and mx.lr_scheduler.FactorScheduler) , clip_gradient   and mx.init.Xavier. 
I guess they have not been implemented in R yet, right?

**Comment by pluskid** [comment]
@Gelu74 Do you mean R or Julia? You may open an issue in the main MXNet repo if it is related to R. :)

**Comment by Gelu74** [comment]
uppss
sorry
