### ISSUE TITLE
Julia upstream is now incompatible with MXNet

### ISSUE THREAD

**Issue by vchuravy** [dmlc/MXNet.jl#59]
Julia upstream is quite a bit stricter about methods and so travis builds started failing.

@pluskid I started looking into it, but you are more familiar with the code so I will be focusing on NativeOperators right now.

**Comment by pluskid** [comment]
@vchuravy If you are talking about the failing of Julia nightly on initializers (not allowed to define `call` for abstract types), I have pushed some changes recently to fix it to the master branch.

**Comment by vchuravy** [comment]
Thanks I must have tried it in between :)
