### ISSUE TITLE
ArrayDataProvider without label

### ISSUE THREAD

**Issue by gdkrmr** [dmlc/MXNet.jl#61]
Am I doing anything wrong? Documentation says that labels are optional.

```julia
testprov = mx.ArrayDataProvider(:testprov => rand(10,10))
entry = mx.Variable(:testprov)
hidden = mx.FullyConnected(data = entry, name = :hidden, num_hidden = 10)
ae = mx.LinearRegressionOutput(data = hidden, label = entry, name = :loss)
model = mx.FeedForward(ae, context = mx.cpu())
optimizer = mx.SGD()
mx.fit(model, optimizer, testprov, n_epoch = 10)


INFO: Start training on [CPU0]
INFO: Initializing parameters...
INFO: Creating KVStore...
INFO: Start training...
ERROR: AssertionError: length(labels) == length(preds)
 in update! at /home/gkraemer/.julia/v0.4/MXNet/src/metric.jl:100
 in fit at /home/gkraemer/.julia/v0.4/MXNet/src/model.jl:465
```

**Comment by pluskid** [comment]
Hmm, this is a "bug" or a designing issue with the `Metric` class. It expect you to have separate *data* and *label*, so that it could know which variable to compare with your prediction. I guess a workaround is to still have separate data and label names, but have them point to the same array in the data provider, if that is what you wanted.

**Comment by gdkrmr** [comment]
I can find my way around it, and also you are not forced to use `label` as labels in the output layer, as long as the network graph can be built. 
One question: `mx.LinearRegressionOutput` is the equivalent to the `Mocha.SquareLossLayer`?

**Comment by pluskid** [comment]
Yes, they are similar, with slight difference: `SquareLossLayer` in Mocha is a loss layer, while `LinearRegressonOutput` here is a *output* layer, which is a hybrid of loss function and outputs. So you can actually run prediction with the network without removing the top output (loss) layer, and you will still get the prediction results.

Also the default metric is used to evaluate classification error. You might want to use a different [metric](http://mxnetjl.readthedocs.org/en/latest/api/metric.html). The metric code is written in Julia, so you could also implement one for your own purpose.

**Comment by gdkrmr** [comment]
Very useful, thanks!
