### ISSUE TITLE
Error while running mx.fit

### ISSUE THREAD

**Issue by kleinash** [dmlc/MXNet.jl#64]
Was a noob question and I solved it. Apologies.

**Comment by kleinash** [comment]
I am going to hijack back this issue so not to add another one. 

I am running into issues with the setting the batch. eval_data. 

System: Ubuntu 14.04.4, CUDA 7.5 with current CudNN, Quadro M5000M. 

I am trying to train and test a net I have built. I manage to train it brilliantly, I get a fine training rate, but now that I am trying to evaluate it its requesting a batch value, which I have as 0 and I use my whole batch (800 of 1000 images). 

My code is pretty standard. It runs fine like this: 

```julia 
mx.fit(model, optimizer, train_provider, n_epoch=2, initializer=mx.NormalInitializer(), callbacks=[mx.speedometer(), mx.do_checkpoint(joinpath("./eval/", cp_prefix), save_epoch_0=true)])
```
BUT when I run like this (having successfully imported my data providers)

```julia 
mx.fit(model, optimizer, train_provider, eval_data=eval_provider, n_epoch=1000, initializer=mx.NormalInitializer(), callbacks=[mx.speedometer(), mx.do_checkpoint(joinpath("./eval/", cp_prefix), save_epoch_0=true)]) 
```

I get this error
###
ERROR: LoadError: AssertionError: get_batch_size(opts.eval_data) == batch_size
###

and when I set my batch size to something 0<batch_size<=total; say batch size=10 I get this error: 

###
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [09:12:29] src/engine/./threaded_engine.h:295: [09:12:29] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
###

Not having much luck - what am I doing wrong? 

Thx

**Comment by vchuravy** [comment]
The batch sizes of your eval_provider and your data_provider have to match. Since the eval step is reusing the data providers memory

**Comment by kleinash** [comment]
I set the batch_size right at the beginning - it is the same for all areas.

**Comment by pluskid** [comment]
This is strange. Is your evaluation dataset too small that the total number of samples there is already smaller than the batch size?

**Comment by kleinash** [comment]
My total set has 1000 examples, 800 are training and 20 are evaluation.

**Comment by vchuravy** [comment]
Yes that will be problematic, set your batch_size to 200.  

Can you post how you create `eval_provider` and `data_provider`?

**Comment by kleinash** [comment]
`batch_size=0`

`(128,128,1,20)
(128,128,1,20)
INFO: Start training on [GPU0]
INFO: Initializing parameters...
INFO: Creating KVStore...
INFO: TempSpace: Total 22 MB allocated on GPU0
INFO: Saved checkpoint to './eval/G3DB-test-cp-0000.params'
INFO: Start training...
[09:50:35] /home/.julia/v0.4/MXNet/deps/src/mxnet/dmlc-core/include/dmlc/././logging.h:241: [09:50:35] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
[09:50:35] /home//.julia/v0.4/MXNet/deps/src/mxnet/dmlc-core/include/dmlc/logging.h:241: [09:50:35] src/engine/./threaded_engine.h:295: [09:50:35] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [09:50:35] src/engine/./threaded_engine.h:295: [09:50:35] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_ZN9__gnu_cxx27__verbose_terminate_handlerEv at /usr/bin/../lib/x86_64-linux-gnu/libstdc++.so.6 (unknown line)
unknown function (ip: 0x7f37147106d6)
unknown function (ip: 0x7f3714710703)
unknown function (ip: 0x7f3714763af5)
unknown function (ip: 0x7f37156ae182)
clone at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: (nil))
Aborted (core dumped)`

```julia
train_data = dset_imgs[:,:,1,1:800]
train_labels = dset_labels[:,1:800]
train_labels = reshape(train_labels, length(train_labels), )
test_data = dset_imgs[:,:,1,801:1000]
test_labels = dset_labels[:,801:1000]
test_labels = reshape(test_labels, length(test_labels), )

train_provider = mx.ArrayDataProvider(train_data, train_labels, batch_size=batch_size, shuffle=true)
eval_provider = mx.ArrayDataProvider(test_data, test_labels, batch_size=batch_size, shuffle=true)

```
