### ISSUE TITLE
Current version of CudNN supported?

### ISSUE THREAD

**Issue by kleinash** [dmlc/MXNet.jl#65]
Been stalling on downloading the newer version of Nvidia deep learning SDK. What is the current supported version?

**Comment by pluskid** [comment]
Both cuda 7 and 7.5 should work properly. What is the version you are testing?

**Comment by kleinash** [comment]
I have Cuda 7.5 installed, and working. But got a mail from Nvidia saying that they have updated the CudNN libraries. Doesn't look like a big change, this is the link: 

http://info.nvidianews.com/index.php/email/emailWebview?mkt_tok=3RkMMJWWfF9wsRojs67BZKXonjHpfsX%2F4uwuXKW3iokz2EFye%2BLIHETpodcMS8tjMq%2BTFAwTG5toziV8R7HAKs1v3NsQXBXg

**Comment by pluskid** [comment]
cuDNN v4 should be already supported in mxnet. The beta version of cuDNN v4 came out quite a while ago.

**Comment by kleinash** [comment]
Alrighty. Thank you for getting back to me.
