### ISSUE TITLE
Vague Matrix Mismatch Error. 

### ISSUE THREAD

**Issue by Tumbzilla** [dmlc/MXNet.jl#69]
I keep getting this error, but I can't seem to find what's causing it. 

this is the code I'm running:

```
using MXNet
using HDF5
#----------------- Extract Data from save Files --------------------

println("[Bottom-Up Network] - Program initialized. Loading Training Data.")

Train = h5open("/home/user/Dropbox/Images_for_classification/Data/trainMX.h5", "r") do file
			read(file)
		end
trainData = Train["data"]
trainLabel = Train["label"]

Train = 0



Valid = h5open("/home/user/Dropbox/Images_for_classification/Data/validMX.h5", "r") do file
			read(file)
		end
validData = Valid["data"]
validLabel = Valid["label"]

Valid = 0

gc()

println("[Bottom-Up Network] - Images loaded. Preparing the network.")

#------------------- Define the observation network ----------------------
data = mx.Variable(:data)
label = mx.Variable(:label)
expectation = mx.Variable(:expectation)

rgc = @mx.chain mx.Convolution(data = data, name = :rgc, kernel=(3,3), num_filter = 4) =>
				mx.Activation(act_type = :tanh)

obsV1 = @mx.chain   mx.Convolution(data = rgc, name = :V1, kernel=(10,10), num_filter = 20) =>
					mx.Activation(act_type = :tanh) =>
					mx.Pooling(pool_type = :avg, kernel = (2,2), stride = (2,2))
				
obsV2 = @mx.chain   mx.Convolution(data = obsV1, name = :V2,  kernel = (10,10), num_filter = 50) =>
					mx.Activation(act_type = :tanh) =>
					mx.Pooling(pool_type = :avg, kernel = (2,2), stride = (2,2))
				
obsIT = @mx.chain   mx.FullyConnected(data = obsV2, name = :IT, num_hidden = 500) =>
			mx.Activation(act_type = :tanh)
				
IT2 = @mx.chain mx.FullyConnected(data = obsIT, name = :IT2, num_hidden = 2) =>
		mx.Activation(act_type= :tanh)

Output = mx.SoftmaxOutput(IT2, label, name = :softmax)

batch_size = 100

train_provider= mx.ArrayDataProvider(:data => trainData, :label => trainLabel, batch_size = batch_size, shuffle = true, flat = true)
eval_provider= mx.ArrayDataProvider(:data => validData, :label => validLabel, batch_size = batch_size, shuffle = true, flat = true)

forwardnet = mx.FeedForward(Output, context = mx.gpu())

println("[Bottom-Up Network] - Network is Built! Standby for Training Output.")

optimizer = mx.SGD(lr=0.1, momentum=0.9, weight_decay=0.00001)

mx.fit(forwardnet, optimizer, train_provider, n_epoch=20, eval_data=eval_provider)
```
and this is the output:

```
INFO: Start training on [GPU0]
INFO: Initializing parameters...
INFO: Creating KVStore...
INFO: Start training...
[23:23:08] /home/user/.julia/v0.4/MXNet/deps/src/mxnet/mshadow/mshadow/./././dot_engine-inl.h:431: Check failed: dst.size(0) == sleft[0] && dst.size(1) == sright[1] && sleft[1] == sright[0] dot-gemm: matrix shape mismatch

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f4fbad4e2f1)
_ZN7mshadow4expr9DotEngineINS_2sv6savetoENS_3gpuELi2ELi2ELi2ELb0ELb1EfE4EvalEPNS_6TensorIS4_Li2EfEERKS7_SA_f at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN7mshadow4expr16ExpComplexEngineINS_2sv6savetoENS_6TensorINS_3gpuELi2EfEENS0_6DotExpIS6_S6_Lb0ELb1EfEEfE4EvalEPS6_RKS8_ at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN7mshadow4expr9ExpEngineINS_2sv6savetoENS_6TensorINS_3gpuELi2EfEEfE4EvalINS0_6DotExpIS6_S6_Lb0ELb1EfEEEEvPS6_RKNS0_3ExpIT_fLi7EEE at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN7mshadow4expr9RValueExpINS_6TensorINS_3gpuELi2EfEEfE8__assignINS0_6DotExpIS4_S4_Lb0ELb1EfEELi7EEERS4_RKNS0_3ExpIT_fXT0_EEE at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN7mshadow6TensorINS_3gpuELi2EfEaSINS_4expr6DotExpIS2_S2_Lb0ELb1EfEELi7EEERS2_RKNS4_3ExpIT_fXT0_EEE at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN5mxnet2op16FullyConnectedOpIN7mshadow3gpuEfE7ForwardERKNS_9OpContextERKSt6vectorINS2_5TBlobESaIS9_EERKS8_INS_9OpReqTypeESaISE_EESD_SD_ at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZZN5mxnet13GraphExecutor14GetOpExecEntryEjENKUlNS_10RunContextENS_6engine18CallbackOnCompleteEE_clES1_S3_ at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNSt17_Function_handlerIFvN5mxnet10RunContextENS0_6engine18CallbackOnCompleteEEZNS0_13GraphExecutor14GetOpExecEntryEjEUlS1_S3_E_E9_M_invokeERKSt9_Any_dataS1_S3_ at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNKSt8functionIFvN5mxnet10RunContextENS0_6engine18CallbackOnCompleteEEEclES1_S3_ at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN5mxnet6engine14ThreadedEngine15ExecuteOprBlockENS_10RunContextEPNS0_8OprBlockE at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN5mxnet6engine23ThreadedEnginePerDevice9GPUWorkerILN4dmlc19ConcurrentQueueTypeE0EEEvibPNS1_17ThreadWorkerBlockIXT_EEE at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS0_8OprBlockEbENKUlvE1_clEvENKUlvE_clEv at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNSt17_Function_handlerIFvvEZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS2_8OprBlockEbENKUlvE1_clEvEUlvE_E9_M_invokeERKSt9_Any_data at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNKSt8functionIFvvEEclEv at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNSt12_Bind_simpleIFSt8functionIFvvEEvEE9_M_invokeIJEEEvSt12_Index_tupleIJXspT_EEE at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNSt12_Bind_simpleIFSt8functionIFvvEEvEEclEv at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNSt6thread5_ImplISt12_Bind_simpleIFSt8functionIFvvEEvEEE6_M_runEv at /home/user/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
unknown function (ip: 0x7f51d0cf9a60)
unknown function (ip: 0x7f51d1c58182)
clone at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: (nil))
Aborted (core dumped)
```

the data being fed in is of shape (100,100,1,42000) in julia, and the labels are of shape (42000,). The net is fed batches of 100 samples.

**Comment by pluskid** [comment]
This is strange. I'm also wondering what is that `flat=true` for `ArrayDataProvider`?

**Comment by Tumbzilla** [comment]
Ah, I forgot to mention. I modified `AbstractDataProvider` so that it mimics the behaviour of `get_mnist_data` during my troubleshooting. 

Otherwise, the dimensions of my data are collapsed down to (10000,42000) and (1,42000). I originally thought this was the issue, since the convolution layers have 2D kernels. I get the exact same output with or without my edits

**Comment by pluskid** [comment]
This is quite mysterious. Are you able to identify whether it happens at the beginning of the iterations or after a couple of mini-batches?

**Comment by Tumbzilla** [comment]
I haven't been able to. I haven't been able to set `MXNET_ENGINE_TYPE=NaiveEngine` in order to get a serialized error output, either.

I've also tried running it on CPU, with libmxnet.so compiled with and without CUDA and CuDNN. All of these result in the same error.

**Comment by pluskid** [comment]
@Tumbzilla Maybe you can add a print statement to the function of the array data provider just to tell on which iteration the error occurred?

**Comment by Tumbzilla** [comment]
@pluskid I added `println(idx)` to `Base.next(provider :: ArrayDataProvider, state :: ArrayDataProviderState)` like so:

```
function Base.next(provider :: ArrayDataProvider, state :: ArrayDataProviderState)
  idx = state.curr_idx:Base.min(state.curr_idx+provider.batch_size-1, provider.sample_count)
  println(idx)
  return (ArrayDataBatch(idx), ArrayDataProviderState(idx.stop+1))
end
```

I believe that it fails on the first run through given that it fails after loading the first batch. I have bolded the relevant output below:

<pre>
INFO: Recompiling stale cache file /home/patricklaflamme/.julia/lib/v0.4/MXNet.ji for module MXNet.
[Bottom-Up Network] - Program initialized. Loading Training Data.
[Bottom-Up Network] - Images loaded. Preparing the network.
MXNet.mx.SymbolicNode(MXNet.mx.MX_SymbolHandle(Ptr{Void} @0x00000000027b3ef0))
[Bottom-Up Network] - Network is Built! Standby for Training Output.
INFO: Start training on [GPU0]
INFO: Initializing parameters...
INFO: Creating KVStore...
INFO: Start training...
<b>1:100</b>
[09:52:54] /home/patricklaflamme/.julia/v0.4/MXNet/deps/src/mxnet/mshadow/mshadow/./././dot_engine-inl.h:431: Check failed: dst.size(0) == sleft[0] && dst.size(1) == sright[1] && sleft[1] == sright[0] dot-gemm: matrix shape mismatch

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fe5cedde2f1)
_ZN7mshadow4expr9DotEngineINS_2sv6savetoENS_3gpuELi2ELi2ELi2ELb0ELb1EfE4EvalEPNS_6TensorIS4_Li2EfEERKS7_SA_f at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN7mshadow4expr16ExpComplexEngineINS_2sv6savetoENS_6TensorINS_3gpuELi2EfEENS0_6DotExpIS6_S6_Lb0ELb1EfEEfE4EvalEPS6_RKS8_ at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN7mshadow4expr9ExpEngineINS_2sv6savetoENS_6TensorINS_3gpuELi2EfEEfE4EvalINS0_6DotExpIS6_S6_Lb0ELb1EfEEEEvPS6_RKNS0_3ExpIT_fLi7EEE at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN7mshadow4expr9RValueExpINS_6TensorINS_3gpuELi2EfEEfE8__assignINS0_6DotExpIS4_S4_Lb0ELb1EfEELi7EEERS4_RKNS0_3ExpIT_fXT0_EEE at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN7mshadow6TensorINS_3gpuELi2EfEaSINS_4expr6DotExpIS2_S2_Lb0ELb1EfEELi7EEERS2_RKNS4_3ExpIT_fXT0_EEE at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN5mxnet2op16FullyConnectedOpIN7mshadow3gpuEfE7ForwardERKNS_9OpContextERKSt6vectorINS2_5TBlobESaIS9_EERKS8_INS_9OpReqTypeESaISE_EESD_SD_ at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZZN5mxnet13GraphExecutor14GetOpExecEntryEjENKUlNS_10RunContextENS_6engine18CallbackOnCompleteEE_clES1_S3_ at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNSt17_Function_handlerIFvN5mxnet10RunContextENS0_6engine18CallbackOnCompleteEEZNS0_13GraphExecutor14GetOpExecEntryEjEUlS1_S3_E_E9_M_invokeERKSt9_Any_dataS1_S3_ at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNKSt8functionIFvN5mxnet10RunContextENS0_6engine18CallbackOnCompleteEEEclES1_S3_ at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN5mxnet6engine14ThreadedEngine15ExecuteOprBlockENS_10RunContextEPNS0_8OprBlockE at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZN5mxnet6engine23ThreadedEnginePerDevice9GPUWorkerILN4dmlc19ConcurrentQueueTypeE0EEEvibPNS1_17ThreadWorkerBlockIXT_EEE at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS0_8OprBlockEbENKUlvE1_clEvENKUlvE_clEv at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNSt17_Function_handlerIFvvEZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS2_8OprBlockEbENKUlvE1_clEvEUlvE_E9_M_invokeERKSt9_Any_data at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNKSt8functionIFvvEEclEv at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNSt12_Bind_simpleIFSt8functionIFvvEEvEE9_M_invokeIJEEEvSt12_Index_tupleIJXspT_EEE at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNSt12_Bind_simpleIFSt8functionIFvvEEvEEclEv at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
_ZNSt6thread5_ImplISt12_Bind_simpleIFSt8functionIFvvEEvEEE6_M_runEv at /home/patricklaflamme/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so (unknown line)
unknown function (ip: 0x7fe7e4d89a60)
unknown function (ip: 0x7fe7e5ce8182)
clone at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: (nil))
Aborted (core dumped)
</pre>
I'm wondering if it's a problem with the infer_shape function? Is there a way to check the dimensions of the weight matrices?

**Comment by pluskid** [comment]
You can visualize the network (as shown in [the example here](https://github.com/dmlc/MXNet.jl/blob/master/examples/char-lstm/visualize.jl)) using GraphViz. As you can see from [here](https://github.com/dmlc/MXNet.jl/blob/master/src/visualize.jl#L19), you can pass in `input_shapes` when doing visualization (the information from data provider `provide_data`), and then the shapes of input / output of each layer will be presented in the figure IIRC.

If you want to see the shapes of the weights. You can do `infer_shapes` like something [here](https://github.com/dmlc/MXNet.jl/blob/master/src/model.jl#L98). The `arg_shapes` will be an array of shapes with the correspondence to the names from `list_arguments(self.arch)`. You will be able to tell which one is which from the names.

**Comment by Tumbzilla** [comment]
So from the visualization, it appears the weights are only displayed as 3D tensors. Perhaps the issue is the fact that I'm inputting 4D data, on account of the 4th dimensions being the sample number?

![viz](https://cloud.githubusercontent.com/assets/7294112/14215051/6f9da7d0-f7f5-11e5-9199-3f6d5b646f03.png)

**Comment by Tumbzilla** [comment]
scratch that. Doing the same for the Lenet example, which runs correctly on my machine, gives me the same result.

**Comment by Tumbzilla** [comment]
I've found the issue. I ran `infer_shapes` as you suggested, and it seems to infer the wrong shape for the weights of the first fully connected layer.

this is the code I used to get this info: 

```
println(mx.infer_shape(forwardnet.arch; :data => (100,100,1,100), :label => (100,)))
```

and it gave me this output:

<pre>
(Tuple[(100,100,1,100),(3,3,1,4),(4,),(9,9,4,20),(20,),(10,10,20,50),(50,),<b>(18,500)</b>,(500,),(500,2),(2,),(100,)],Tuple[(2,100)],Tuple[])
</pre>

once again, I have bolded the relevant issue.

How would I go about fixing this?

**Comment by pluskid** [comment]
@Tumbzilla I see the problem. It is because the output of V2 is 4D tensor, while IT (a fully-connected layer) expects 2D tensor. You are expected to insert a `Flatten` layer in between them. This is what our lenet example is:

```julia
# first fully-connected
fc1   = @mx.chain mx.Flatten(data=conv2) =>
                  mx.FullyConnected(num_hidden=500) =>
                  mx.Activation(act_type=:tanh)
```

Notice the `Flatten` before `FullyConnected`. But definitely the error message should be earlier and clearer. I will try to add a check in the upstream libmxnet to print more friendly error message in this case.

**Comment by Tumbzilla** [comment]
@pluskid Ah that explains everything. Thanks so much, your help was greatly appreciated.

**Comment by pluskid** [comment]
@Tumbzilla You are welcome! Also thanks for your detailed report that helps us to find a bug!
