### ISSUE TITLE
Error while running lenet example with batch size 100

### ISSUE THREAD

**Issue by salonip** [dmlc/MXNet.jl#70]
Hi,I am using Ubuntu 14.04 cuda7.0 GPU GeForce GTX 750 Ti.When I run examples/mnist/lenet.jl in julia with batch size 100 I get following error

###
/home/durjoysenmaitra/mxnet/dmlc-core/include/dmlc/././logging.h:241: [11:36:30] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
[11:36:30] /home/durjoysenmaitra/mxnet/dmlc-core/include/dmlc/logging.h:241: [11:36:30] src/engine/./threaded_engine.h:295: [11:36:30] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [11:36:30] src/engine/./threaded_engine.h:295: [11:36:30] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_ZN9__gnu_cxx27__verbose_terminate_handlerEv at /home/saloni/Documents/Julia Codes/julia/bin/../lib/julia/libstdc++.so.6 (unknown line)
unknown function (ip: 0x7f96bb708996)
unknown function (ip: 0x7f96bb7089e1)
unknown function (ip: 0x7f96bb732848)
unknown function (ip: 0x7f96bb9ff182)
clone at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: (nil))
Aborted (core dumped)
###

But when I run the same code with batch size 200,it works.I don't understand the reason.
The example in python works fine on GPU with batchsize 100 though!

How to solve this?

**Comment by kleinash** [comment]
I am having a similar issue - Quadro K5000M; Ubuntu 14.04; Cuda 7.5. When I give a batch size I get a memory error. But when I use batch size = 0 it works but immediately settles on a learning rate. The batch size of 8 worked initially - but when I try again it stops working (memory error) 

How does MXNet.jl release GPU memory after using? 

My net: 

```julia 
using MXNet

batch_size = 8
workspace = 4096

#----- build CNN
data = mx.Variable(:data)
label = mx.Variable(:label)
# first conv
conv1 = @mx.chain mx.Convolution(data=data, kernel=(5,5), num_filter=20, workspace=workspace)  =>
                  mx.Activation(act_type=:relu) 
                  mx.Pooling(pool_type=:max, kernel=(2,2), stride=(2,2))
# second conv
conv2 = @mx.chain mx.Convolution(data=conv1, kernel=(5,5), num_filter=50, workspace=workspace) =>
                  mx.Activation(act_type=:relu) 
                  mx.Pooling(pool_type=:max, kernel=(2,2), stride=(2,2))
                  # first fully-connected
fc1   = @mx.chain mx.Flatten(data=conv2) =>
                  mx.FullyConnected(num_hidden=500) =>
                  mx.Activation(act_type=:relu)
# second fully-connected
fc2   = mx.FullyConnected(data=fc1, num_hidden=10) 
# third fully-connected
fc3   = mx.FullyConnected(data=fc2, num_hidden=2) 
# softmax loss
net = mx.SoftmaxOutput(data=fc3, name=:softmax)

#----- load data
include("G3DB_data.jl")
train_provider = get_data(batch_size)

# ------ fit model
model = mx.FeedForward(net, context=mx.gpu())
# optimizer
optimizer = mx.ADAM(lr=0.00000000001)
# optimizer = mx.SGD(lr=0.1, momentum=0.9, weight_decay=0.00001)
# fit parameters

mx.fit(model, optimizer, train_provider, n_epoch=10000)
# mx.fit(model, optimizer, train_provider, n_epoch=20, eval_data=eval_provider)
```

output:
###
size(train_data) = (28,28,1,800)
(28,28,1,8)
INFO: Start training on [GPU0]
INFO: Initializing parameters...
INFO: Creating KVStore...
INFO: Start training...
[17:04:12] /home/ashley/.julia/v0.4/MXNet/deps/src/mxnet/dmlc-core/include/dmlc/././logging.h:241: [17:04:12] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
[17:04:12] /home/ashley/.julia/v0.4/MXNet/deps/src/mxnet/dmlc-core/include/dmlc/logging.h:241: [17:04:12] src/engine/./threaded_engine.h:295: [17:04:12] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [17:04:12] src/engine/./threaded_engine.h:295: [17:04:12] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_ZN9__gnu_cxx27__verbose_terminate_handlerEv at /usr/bin/../lib/x86_64-linux-gnu/libstdc++.so.6 (unknown line)
unknown function (ip: 0x7f8fbe7fb6d6)
unknown function (ip: 0x7f8fbe7fb703)
unknown function (ip: 0x7f8fbe84eaf5)
unknown function (ip: 0x7f8fbf799182)
clone at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: (nil))
[Finished in 8.9s with exit code -6]
[cmd: ['julia', '/home/ashley/G3DB/filtered_G3DB/src/G3DB_cnn.jl']]
[dir: /home/ashley/G3DB/filtered_G3DB/src]
[path: /opt/ros/indigo/bin:/home/ashley/anaconda3/bin:/usr/local/cuda-7.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games]
###

**Comment by pluskid** [comment]
Just to give some context. MXNet.jl use Julia finalizer to release GPU memory. This is not a very good way, but we currently have no better way of doing this automatically without bothering the end user too much. If you constantly see out-of-memory-error on GPUs, typically forcing call to Julia GC might help to resolve the issue.

**Comment by salonip** [comment]
worked!thanks

**Comment by kleinash** [comment]
Sorry - Im a noob - I am getting an error saying that jl_gc_collect() is not defined - should I be importing something before running it?

**Comment by vchuravy** [comment]
@kleinash Which version of julia are you running? And where are you calling `jl_gc_collect` from?
Normally `gc()` should do the job.

**Comment by kleinash** [comment]
V0.4.2. Its just odd that it would work with the full set and when I put in a batch number it bombs. 
I thought to put it in after calling the train_provider, but then I guess I wipe out the input info. So where would you call it? 

```julia 
train_provider = get_data(batch_size)
model = mx.FeedForward(net, context=mx.gpu())
optimizer = mx.ADAM(lr=0.001)
mx.fit(model, optimizer, train_provider, n_epoch=10)
```

**Comment by salonip** [comment]
`gc()
  for i_epoch = 1:opts.n_epoch
 	
	gc()
    time_start = time()
    reset!(opts.eval_metric)

    op_state.curr_epoch = i_epoch
    op_state.curr_batch = 0

    # invoke callbacks on iteration 0
    _invoke_callbacks(self, opts.callbacks, op_state, AbstractBatchCallback)

    for batch in eachbatch(data)
     gc()`
snippet from my  /home/saloni/.julia/v0.4/MXNet/src/model.jl looks like this

**Comment by kleinash** [comment]
Is that after invoking mx.fit() ?

**Comment by pluskid** [comment]
I think @salonip modified the MXNet.jl source code directly. Alternatively, you can define a callback (see [doc here](http://mxnetjl.readthedocs.org/en/latest/api/callback.html)) that calls `gc()` every some mini-batches.

**Comment by salonip** [comment]
oh great! @pluskid Thanks!
