### ISSUE TITLE
Documentation of `Concat`

### ISSUE THREAD

**Issue by vchuravy** [dmlc/MXNet.jl#72]
I recently build based on `mx.Concat` and I was following the API documentation at http://mxnetjl.readthedocs.org/en/latest/api/symbolic-node.html#Concat 

```julia
data = mx.Variable(:data)
data2 = mx.Variable(:data2)

mx.Concat(data = [data, data2], num_args=2)
```

This fails with:
```
ERROR: MXNet.mx.MXError("value 0for Parameter num_args should be greater equal to 1")
 [inlined code] from /home/wallnuss/.julia/v0.4/MXNet/src/base.jl:57
 in __Concat#40__ at /home/wallnuss/.julia/v0.4/MXNet/src/symbolic-node.jl:562
```

On the other hand, the undocumented(besides in the examples)
```
mx.Concat(data1, data)
```

works just fine.

**Comment by pluskid** [comment]
Might be a bug in the auto-importing code. I will try to have a look.
