### ISSUE TITLE
Saving the net visulization 

### ISSUE THREAD

**Issue by kleinash** [dmlc/MXNet.jl#75]
Hi,

where does: `mx.to_graphviz(net)` save the dot file? 

Thx

**Comment by pluskid** [comment]
It returns the dot description as a string, so you can write to wherever you want.

**Comment by kleinash** [comment]
i.e. 
```julia
net_dot = mx.to_graphviz(net) 
net_file = open("net.dot", "w")
write(net_file, net_dot)
```
