### ISSUE TITLE
Saving and loading the model

### ISSUE THREAD

**Issue by kleinash** [dmlc/MXNet.jl#78]
Hi, How do I save and load the model after training - like here:

https://github.com/dmlc/mxnet/issues/479
http://myungjun-youn-demo.readthedocs.org/en/latest/python/model.html#save-the-model 

Thx

**Comment by vchuravy** [comment]
You will need a callback to save the model and then `load_checkpoint` to load the model from disk. 

```
mx.fit(..., callbacks=[mx.do_checkpoint(prefix, save_epoch_0=true)]
mx.load_checkpoint(prefix, epoch)
```

**Comment by kleinash** [comment]
If I do this:

```julia

prefix = "model"
mx.fit(model, optimizer, train_provider, n_epoch=2, callbacks=[mx.do_checkpoint(prefix), save_epoch_0=true])
```
ERROR: LoadError: MethodError: `convert` has no method matching convert(::Type{MXNet.mx.AbstractCallback}, ::Bool)
This may have arisen from a call to the constructor MXNet.mx.AbstractCallback(...),
since type constructors fall back to convert methods.

I get this error:

**Comment by vchuravy** [comment]
You have a typo in `[mx.do_checkpoint(prefix), save_epoch_0=true])` you have to do `[mx.do_checkpoint(prefix, save_epoch_0=true)])`

**Comment by kleinash** [comment]
Aaaah thank you kindly :) 

Can I ask here how I would access the predicted values of my model? Having the actual values stored in an H5 file.

**Comment by kleinash** [comment]
Nope I see it - I am guessing they are in the params files - just have to figure out how to access them now.

**Comment by vchuravy** [comment]
The params file contains the weights not the predicted values. See
https://github.com/dmlc/MXNet.jl/blob/master/examples/imagenet/ijulia-pretrained-predict/Prediction%20with%20Pre-trained%20Model.ipynb
for
how to load a model and how to use it to predict values.

**Comment by kleinash** [comment]
Alrighty thanks muchly.. maybe I can look into plotting those weights to see any patterns. Thank you again.

**Comment by vchuravy** [comment]
If you do any visualization of the weights, feel free to share the code :)
It would be super cool to have something like
https://github.com/ericjang/tdb

**Comment by kleinash** [comment]
alrighty then :)
